<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   config.php
 *		projet   définition des messages
 *
 *		version  1.0
 *		auteur   laporte
 *		creation 05/04/2007
 *		modif
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"Configuration de l'intranet",
"Personnalisation",
"Base de données",
"Menus",
"Sécurité",
"Connexion persistante",
"Création de compte",
"par les utilisateurs",
"Durée de validité",
"des comptes (aaaa-mm-jj)",
"Filtrage IP",
"Mode DEBUG",
"Mode DEMO",
"connexions multiples sous le même ID",
"Mot de passe",
"caractére(s)",
"Délai des pages",
"minutes",
"Délai des liens",
"jours",
"Données",
"Taille des fichiers",
"Quotas disque",
"Durée des logs",
"Durée des stats",
"Durée des post-it",
"semaines",
"Affichage",
"Menus",
"2 colonnes,gauche,droite",
"Espacement",
"pixel(s)",
"Page d'accueil",
"flash info par défaut",
"Données par page",
"Nombre de pages",
"Derniers messages",
"forum style egroup",
"Documents autorisés",
"Modifier",
"Créer",
"- extension",
"ajouter un document",
"pour valider la configuration.",
"pour revenir à l'accueil.",
"Configuration de la base de données",
"Centres constitutifs",
"visible",
"invisible",
"supprimer",
"ajouter un enregistrement",
"Groupes utilisateurs",
"droits étendus",
"droits limités",
"Promotions",
"Matières",
"<em>afin de personnaliser votre intranet, veuillez compléter le formulaire suivant</em>",
"Prométhée, l'ENT « clef en main » Libre et gratuit",
"Bienvenue sur votre intranet",
"Veuillez entrer votre identifiant ou votre email ainsi que votre mot de passe pour vous connecter.",
"Erreur à la création de \'%1\' vérifiez que vous possédez les droits d'écriture.",
"Erreur à la création de %1 vérifiez que vous possédez les droits d'écriture.",
"Bravo, vous avez réussi à paramétrer votre intranet !<br/><br/>
Il vous reste à créer les comptes<br/>
%1 des utilisateurs avec phpMyAdmin (base %2, table user_id).<br/>
%3 des %4 avec phpMyAdmin (base %5, table user_student).<br/><br/>
Pour tester l'intranet, utilisez le compte administrateur \'%6\' (pas de mot de passe).<br/>
Pour vous connecter maintenant cliquez <a href=\'%7\'>ici</a>.",
"Options",
"Choisissez un menu",
"nouvel intitulé",
"sous menu",
"ne pas afficher le lien",
"afficher le lien",
"Personnalisation de l'intranet %1/2",
"Attention veuillez indiquer le nom de votre établissement.",
"Le \'nom\' de votre établissement est utilisé pour créer un répertoire images/logos/\'nom\' où seront copiés le logo de votre établissement (logo01.jpg) ainsi que celui de votre région (logo02.jpg).",
"Nom établissement",
"obligatoire",
"Taille maximale conseillée du logo établissement 700 x 110.",
"Logo établissement",
"Taille maximale conseillée du logo région 100 x 50.",
"Logo région",
"La couleur du thème est celle utilisée pour l'intranet. Elle doit correspondre à votre charte graphique.",
"Attention: veuillez indiquer l'adresse de votre établissement.",
"Adresse",
"Attention: veuillez indiquer le téléphone de votre établissement.",
"N° téléphone",
"Fax",
"Site web",
"Email de l'administrateur",
"Indiquez ici le type de votre établissement",
"Suivant >>",
"La base de données va être paramétrée en fonction du type de votre établissement.<br/>Veuillez indiquer les centres constitutifs (ie collège et lycée) qui composent votre établissement.",
"Type établissement",
"Pour terminer l'installation cliquez ici",
"Envoyer",
"Erreur création %1 (%2)",
"Personnalisation de l'intranet",
"Choisissez une configuration",
"Thème",
"appliquer aux menus",
"Puces graphiques",
"Fond graphique",
"appliquer à la page",
"Barre des Titres",
"Couleur du bandeau",
"Adresse",
"Logos",
"<a href=\'%1\'>logo principal</a>",
"Gauche",
"Centré",
"Droite",
"Titre de fenêtre",
"Message d'accueil",
"Message de connexion",
"aide",
"modification du lien",
"nouveau lien",
"insertion",
"modification",
"Gestionnaire de menus",
"Statut",
"Auteur",
"Liste",
"Attention l'intitulé doit être renseigné.",
"Intitulé",
"Attention l'url doit être renseignée.",
"URL",
"Accès visible",
"Autorisations",
"Fermer le lien",
"Accès anonyme",
"ajouter un lien",
"pour revenir sur la page précédente.",
"- public",
"validité",
"<a href=\'%1\' onclick=\'window.open(this.href, '_blank'); return false;\'>logo région</a>",
"Langues autorisées",
"Image",
"ajouter un menu",
"Modifier le menu",
"nouveau menu",
"Texte",
"Alignement",
"Affichage",
"fermer le menu",
"défilement",
"Bienvenue sur la page %1.",
"Pictogramme",
"Contenu",
"SMS",
"Service SMS",
"Webmestre",
"Installer",
"Désinstaller",
"P2P",
"Clef",
"Connexion",
"Obtenir une clef",
"Partage",
"Maintenance",
"Choisissez un centre",
"Filtrage",
"Filtrage des accès",
"du",
"au",
"aaaa-mm-jj",
"Encodage",
"== personnalisé ==",
"Backoffice",
"trier les items",
"Activer",
"Désactiver",
"Taille",
"Ko",
"Serveur",
"Configuration du P2P",
"Configuration des menus",
"Configuration des mot-clefs",
"Mot-clefs",
"Synchronisation",
"lancer la synchronisation",
"Documents",
"Annuaire",
"Robot d'indexation",
"Code postal",
"Fuseau horaire",
"Architecture",
"bits",
"Nouveau",
"Répondre",
"Enregistrer",
"Annuler",
"Couleur bandeau menu haut",
"Emploi du temps",
"Vacances",
"Configuration semaine paire/impaire",
"Configuration des vacances",
"Couleur",
"Semaine",
"au",
"Matières de la promotion",
"Enseignants de la promotion",
"Motifs d'absence",
"Pour spécifier que l'absence ne doit pas être comptabilisée ajouter [NC] dans l'intitulé du motif",
"Nom du centre",
"Nom du groupe",
"Code",
"Nom de la formation",
"Nom de la matière",
"Couleur",
"Nom du motif",
"Salles",
"Nom de la salle",
"Pôles",
"Année d'obtention du diplôme",
"Nom du pôle",
"Matières par niveau",
"Paramètres",
"Valider",
"Il y a eu une erreur, merci de réessayer",
"Le paramètre à bien été modifié",
"Code",
"Valeur",
"Commentaire",
"Vider le cache",
"Le cache à bien été vidé",
"Il y a eu une erreur",
"Configuration des périodes",
"Nouvelle configuration",
"Renommer la configuration",
"Nom de la configuration",
"Ville",
"Choisir un fichier",
"Choisir",
"Utiliser comme configuration par défaut",
"Logo large",
"Logo carré",
"Configuration actuelle",
"Image de la signature du chef d'établissement",
"Favicon",
"Image de 100 pixels sur 100 pixels, de préférence au format png",
"Supprimer la configuration",
"Êtes-vous sûr de ce que vous faites ?",
"Activé",
"Désactivé",
"Logo large en version sombre",
"Logo carré en version sombre",
"Un code font-awesome est requis (exemple: <u>fa-cog</u> pour <i class=\"fas fa-cog\"></i>)",
"Retour",
"Personalisation CSS du thème"

);
//---------------------------------------------------------------------------
?>
