<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : resource.php
 *		projet   : définition des messages
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 11/04/2007
 *		modif    : 
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"<strong>Ressources en ligne</strong>",
"Les ressources sont disponibles sous différents <a href=\'#\' onclick=\'popWin('format.php', '350', '200'); return false;\'>formats</a>.",
"choisissez un serveur de ressources :",
"répertoire racine",
"Modifier",
"Créer",
"ajouter un dossier",
"<strong>Taille</strong>",
"répertoire parent",
"ajouter",
"Envoyer",
"Renommer",
"ajouter un document",
"<strong>Gestion des Documents::%1</strong><br/><em>Veuillez compléter le formulaire suivant pour paramétrer une ressource</em>",
"<strong>Statut :</strong>",
"<strong>Dossier :</strong>",
"<strong>Ressources :</strong>",
"<strong>Fermer la ressource</strong>",
"<strong>Modérateur</strong>",
"<strong>Rédacteur</strong>",
"<strong>Lecteurs</strong>",
"aucun",
"l'utilisateur doit être préalablement déclaré comme modérateur ou rédacteur.",
"pour modifier une ressource.",
"pour annuler et quitter.",
"<strong>Ressources en ligne::Fiche</strong><br/><em>Veuillez poster votre ressource en complétant le formulaire suivant</em>",
"modification",
"nouvel enregistrement",
"<strong>Titre :</strong>",
"<strong>URL :</strong>",
"<strong>langue :</strong>",
"<strong>Description :</strong>",
"<strong>Mots clef :</strong>",
"<strong>Auteur :</strong>",
"<strong>Licence :</strong>",
"<strong>Contenu :</strong>",
"<strong>Niveau :</strong>",
"<strong>Matières :</strong>",
"pour enregistrer votre saisie.",
"<strong>Gestion des Documents::%1</strong><br/><em>Pour créer un dossier veuillez compléter le formulaire suivant</em>",
"<strong>Fermer le dossier</strong>",
"pour %1 un dossier.",
"pour revenir sur la page des ressources.",
"<strong>Ressources en ligne</strong>",
"créer un nouveau dossier",
"choisissez une ressource :",
"toutes les ressources",
"choisissez un niveau :",
"tous niveaux",
"pour ajouter une ressource.",
"Lancer la recherche",
"tout type de contenu",
"<strong>vus</strong>",
"plus",
"<strong>Créée le :</strong>",
"<strong>Modifiée le :</strong>",
"Suppression de cette ressource ?",
"précédent",
"suivant",
"<strong>Ressources</strong><br/><em>Pour ajouter une annonce, complétez le formulaire suivant</em>",
"effacer le message",
"<strong>Texte</strong>",
"aide",
"pour ajouter une annonce.",
"pour revenir sur la page des ressources.",
"<strong>Espace Ressources %1</strong><br/><em>Veuillez poster votre ressource en complétant le formulaire suivant</em>",
"modification ressource",
"nouvelle ressource",
"transfert",
"insertion",
"ne peut trouver le fichier.",
"<strong>Catégorie :</strong>",
"<strong>Attention :</strong> l'intitulé doit être renseigné.",
"<strong>Intitulé</strong> (le nom de la ressource dans le tableau)",
"<strong>Description</strong> (optionnelle)",
"la taille du fichier est limitée à %1 octets. Veuillez changer de fichier.",
"vous devez indiquer un fichier à télécharger.",
"ce type de fichier n'est pas autorisé.",
"le fichier à télécharger existe déjà sur le serveur. Veuillez changer son nom ou son n° de version.",
"<strong>Attention :</strong> %1",
"<strong>Fichier</strong> (cliquez sur le bouton pour indiquer le fichier à transférer)",
"<strong>Version</strong> (optionnelle : n° de version du fichier)",
"facile,moyen,difficile",
"Niveau des exercices",
"<strong>Partage des ressources</strong> (optionnel)",
"pour revenir sur la page %1.",
"<strong>Ressources en ligne::Fiche</strong>",
"[suivant].[précédent]",
"<a href=\'%1\'>retour</a>",
"<strong>Documents::%1</strong>",
"choisissez une _CLASS :",
"choisissez un groupe :",
"toutes les _CLASSs",
"tous les groupes",
"nouveau",
"<strong>Document</strong>",
"<strong>date</strong>",
"Format",
"modifier",
"modifier la ressource",
"fermer",
"ouvrir",
"<a href=\'%1\'>rechercher</a> une ressource.",
"Suppression de %1 ?",
"<strong>Version :</strong>",
"<strong>Ressource :</strong>",
"%1 commentaire%s",
"Ne peut renommer le répertoire : %1",
"Ne peut effacer le répertoire : %1",
"Ne peut effacer le fichier : %1",
"Ne peut renommer le fichier : %1",
"Suppression du fichier ?",
"Mot clef",
"<strong>Fiche :</strong>",
"Vous trouverez ici une banque de ressources en ligne.",
"%1 dossier%s",
"%1 document%s",
"copier le fichier",
"Copier",
"déplacer le fichier",
"Déplacer",
"<strong>Dernier téléchargement :</strong>",
"fermer cette fenêtre",
"valider la saisie.",
"<strong>Note</strong>",
"<strong>Date de validité</strong> (optionnelle)",
"par date,par nom,par taille",
"Connexion",
"<strong>Autorisation</strong>",
"commentaires",
"<strong>Priorité :</strong>",
"Importante,Haute,Très haute",
"<strong>Avertir</strong>",
"ne pas avertir,modérateur,post-it,email",
"[%1] dépôt de fichier",
"Un nouveau fichier a été déposé dans : \'%1\' le %2.",
"document collaboratif",
"Verouiller le document",
"<strong>Verrouillé par :</strong> %1<br/><strong>Limite :</strong> %2",
"<strong>Verrou</strong>",
"heure(s)",
"RSS",
"<strong>Utilisabilité</strong>",
"Visuel,Auditif,Kinesthésique",
"%1 dans",
"ou",
"<strong>Menu</strong>",
"Pièce Jointe",
"(partie %1)",
"<strong>Centre :</strong>",
"tous les centres",
"porte-documents",
"ajouter au porte-documents",
"Vous avez actuellement %1 fichier%s dans votre porte-documents.",
"Que souhaitez-vous faire :",
"exporter dans un fichier compressé,copier dans mon Espace de Travail",
"Fichier compressé <a href=\'%1\'>disponible</a> au format gz.",
"Niveau d'importance",
"<strong>Code couleur</strong>",
"supprimer",
"ressources|répertoire",
"<strong>Préférences</strong>",
"Dossier privé",
"RAZ",
"Partage multicentres",
"[nouveau]",
"[répondre]",
"[valider]",
"[annuler]"

);
//---------------------------------------------------------------------------
?>