<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : student.php
 *		projet   : définition des messages
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 21/03/2007
 *		modif    :
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"Gestion des ACL::%1",
"Choisissez un centre",
"choisissez une catégorie :",
"Groupe :",
"utilisateurs connectés",
"déconnecter tout le monde !",
"dernière connexion :",
"fermer cette fenêtre",
"choisissez une _CLASS",
"Toutes les _CLASSs",
"Basculer dans les anciens _STUDENT",
"Rebasculer en _STUDENT",
"Donner un login de connexion",
"pour valider les modifications.",
"toutes les catégories",
"Accéder à l'Espace Numérique de Travail",
"Le site est provisoirement inaccessible pour cause de maintenance.<br/>Merci de bien vouloir revenir plus tard.",
"L'installation n'a pas encore été effectuée.<br/>Si vous êtes bien le webmaster de ce site, <a href=\'%1\'>cliquez ici</a> pour paramétrer l'intranet.",
"Pas encore de compte ? Vous pouvez en <a href=\'%1\'>créer un</a>.",
"Connexion non autorisée : le site est actuellement en maintenance.",
"Erreur : compte fermé ou en attente de validation.",
"Erreur : l'ID utilisateur ou le mot de passe est incorrect. Veuillez recommencer.",
"Mot de passe :",
"ID Utilisateur :",
"puis cliquez ici",
"Compte utilisateur",
"Attention : vous devez renseigner ce champ.",
"Attention : votre email n'est pas valide. Il doit être composé de la façon suivante : nom@organisme.domaine.",
"Erreur : cet ID est déjà utilisé.",
"Merci de votre participation et à bientôt.",
"ATTENTION :",
"Membre CHS :",
"sans limite de temps",
"Durée :",
"Photo :",
"Pour valider vos modifications",
"Pour revenir sur la page d'accueil",
"session existante : %1",
"Vous avez été déconnecté.",
"Le délai de cette page a expiré : ",
"ajouter un enregistrement",
"promotion :",
"Externe,Interne,1/2 pensionnaire,Campus",
"Boursier",
"Login",
"e-portfolio",
"B2i-C2i",
"stages",
"absences",
"_CLASS :",
"Nom, prénom",
"Date",
"Envoyer un post-it",
"délégué",
"suivant",
"Statut :",
"précédent",
"Personnalisation de l'interface",
"Vous pouvez personnaliser le présentation de votre Espace Numérique de Travail ainsi que vos services.",
"Menus :",
"Puces graphiques :",
"Fond graphique :",
"personnalisation",
"espaces de travail",
"mon blog",
"ma messagerie",
"mes annuaires",
"mon carnet d'adresses",
"pour valider la configuration.",
"pour revenir à l'accueil.",
"Compte _STUDENT",
"Attention: vous devez renseigner ce champ.",
"Prénom",
"Sexe",
"Centre :",
"Valider",
"Né(e) le",
"(aaaa-mm-jj)",
"Adresse",
"CP - Ville",
"Tél :",
"Attention: la saisie doit correspondre à nom@organisme.domaine.",
"Email",
"Régime",
"Bourse",
"Délégué",
"Oui",
"Non",
"jamais connecté",
"Pour revenir sur la liste _STUDENT",
"ajouter un enregistrement",
"Le rôle de chacun::%1",
"tous les centres",
"compte ouvert",
"compte fermé",
"dernière connexion",
"Titre",
"Fonction",
"Validité",
"%1 utilisateur%s en attente de <a href=\'%2\'>validation</a>",
"modifier",
"DROITS",
"Inscrit le",
"Dernière cnx",
"Connecté à",
"messages",
"ressources",
"connections",
"votre mot de passe doit avoir au moins de %1 caractères.",
"votre mot de passe n'est pas renseigné. Pour des raisons de sécurité évidentes nous vous recommandons de compléter le champ de saisie ci-dessous.",
"afficher",
"cacher",
"Signature",
"Avatar",
"Activité",
"Catégorie",
"Autoriser l'accès à la ressource",
"Basculer en liste brûlée",
"rafraîchir",
"Liste _STUDENT",
"Anciens _STUDENT",
"pour effacer ces _STUDENT",
"Sujet : %1",
"Cahier de Texte Numérique",
"dernier accès :",
"Déconnecter %1 ?",
"dernier click :",
"%1 min et %2 s",
"%1 secondes",
"modification",
"nouvel enregistrement",
"obligatoire",
"Homme",
"Femme",
"Anonyme",
"plus",
"Les délégués::%1",
"%1 ans et %2 mois",
"%1 mois et %2 jours",
"%1 jours et %2 heures",
"%1 h et %2 min",
"%1 min et %2 s",
"%1 secondes",
"Langue",
"%1 vous venez de créer un compte<br/>avec comme identifiant : %2<br/>et comme mot de passe : %3 &nbsp;<br/>Ne les oubliez pas !",
"L'administrateur va ouvrir votre compte sous peu. Si vous avez indiqué un email valide, vous serez alors automatiquement prévenu.",
"Vous allez recevoir un email de confirmation contenant votre mot de passe pour accéder à votre compte.",
"Votre compte devra être visité dans les prochaines %1 heures ou il sera automatiquement détruit.",
"Confirmation de votre enregistrement sur %1",
"
Vous trouverez ci-dessous le mot de passe qui vous permettra d'accéder à votre compte sur %1.
Vous pourrez le modifier en cliquant sur le lien \'Mon compte\'.
Votre mot de passe : %2
",
"Mot de passe perdu ?",
"Pas de problème. Indiquez ci-dessous votre ID utilisateur.<br/>Un Email automatique vous sera envoyé avec votre mot de passe.",
"Envoyer un email",
"Basculer %1 en liste brûlée ?",
"Supprimer l'utilisateur %1 ? Toutes les données liées à l'utilisateur seront supprimé ! Cette opération est irreversible",
"changer de _CLASS",
"changer de centre",
"Téléphone :",
"CV n° %1",
"Offre n° %1",
"Nom",
"Bourse",
"Connexion non autorisée : votre accès est momentanément suspendu.",
"filtrer par :|inscription +|inscription -|connexion +|connexion -",
"Gestion des mots de passe",
"Format :",
"Regénérer :",
"Groupes",
"si mdp vide",
"%1 compte%s modifié%s",
"Générer",
"attente validation",
"Dates",
"Droits",
"[%1] Nouvel utilisateur en attente",
"L'utilisateur %1 est en attente de la validation de son compte.",
"%1 connexion%s",
"Matières",
"(%1 ans)",
"Effacer",
"Options",
"Statut",
"O:Valide,N:Ancien élève,A:En attente,D:Démissionaire,E:Exclus",
"export CSV",
"N° ident. :",
"CP",
"Ville",
"Liste parents",
"Mobile :",
"Travail :",
"Tuteurs",
"Nouveau",
"Répondre",
"Valider",
"Annuler",
"Tout",
"Filtrer",
"Retour à la liste des groupes",
"Nom du groupe",
"Liste des _STUDENT du groupe",
"Valider & Nouveau",
"Opération validée, redirection en cours...",
"Valider la suppression du groupe ?",
"Etat",
"Visibles / Archivés",
"Visibles",
"Archivés",
"Promotion",
"Toutes les promotions"

);
//---------------------------------------------------------------------------
?>
