<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : config.php
 *		projet   : messages definition
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 05/04/2007
 *		modif    : 
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"<strong>Intranet settings</strong>",
"customization",
"Database",
"menus",
"<strong>. Safety</strong>",
"Persistent Connection:",
"Account creation:",
"by users",
"Period of validity:",
"of accounts (yyyy-mm-dd)",
"IP Filtering:",
"DEBUG Mode:",
"DEMONSTRATION Mode:",
"(multiple connections with the same ID)",
"Password:",
"character(s)",
"Time delay for pages:",
"minutes",
"Time delay for links:",
"days",
"<strong>. Datas</strong>",
"Files size:",
"Disc quotas:",
"Logs duration:",
"Stats duration:",
"Post-it duration:",
"weeks",
"<strong>. Display</strong>",
"Menus:",
"2 columns,left,right",
"Spacing:",
"pixel(s)",
"Banner page:",
"Default information flash",
"Datas by page:",
"Number of pages:",
"Last messages:",
"egroup style forum",
"<strong>. Authorized documents</strong>",
"Modify",
"Create",
"- extension:",
"add a document",
"validate configuration.",
"back to banner page.",
"<strong>Database Configuration</strong>",
"<strong>. Constitutive centers</strong>",
"visible",
"invisible",
"remove",
"add a record",
"<strong>. Users Groups</strong>",
"extensive rights",
"limited rights",
"<strong>. Classes/Courses/Training</strong>",
"<strong>. Subjects/CU/Modules</strong>",
"<em> in order to customize your Intranet, please fill in the following form</em>",
"Prométhée, the « ready to use » open source VLE 100% free",
"Welcome on the Intranet",
"Please type your ID user and your password to sign in.",
"Error with the creation of \"%1\": check if you have the rights for writing.",
"Error with the creation of %1: check if you have the rights for writing.",
"Well done, you succeeded in customizing your Intranet!<br/><br/>
the only remaining action to proceed is to create the accounts:<br/>
%1 of the users with phpMyAdmin (database %2, table user_id).<br/>
%3 of the %4 with phpMyAdmin (database %5, table user_student).<br/><br/>
To test the Intranet, use the administrator account \"<strong>%6</strong>\" (no password).<br/>
To sign in now click <a href=\"%7\">here</a>.",
"options",
"choose a menu:",
"new heading:",
"<strong>submenu</strong>",
"hide link",
"display link",
"Intranet customization: %1/2",
"<strong>Beware:</strong> please fill in the name of your establishment.",
"The \"name\" of your establishment is used to create a images/logos/\"name\" folder where your establishment's logo (logo01.jpg) and your region's one (logo02.jpg) will be copied.",
"<strong>Establishment name: </strong>",
"mandatory", 
"Advised maximum Size for the establishment logo: 700 X 110.",
"<strong>Establishment logo:</strong>",
"Advised maximum Size for the region logo: 100 X 50.",
"<strong>Region logo:</strong>",
"The Theme color is the one used for the Intranet. It must correspond to your graphic charter.",
"<strong>Beware:</strong> please indicate your establishment's address.",
"<strong>Address:</strong>",
"<strong>Beware:</strong> please indicate your establishment's phone number.",
"<strong>Phone:</strong>",
"<strong>Fax:</strong>",
"<strong>Website:</strong>",
"<strong>Email:</strong>",
"Indicate here your establishment type",
"next >>",
"The data base will be customized according to your establishment type.<br/>Please indicate the constitutive centers (ie: Junior high school and high school) which are parts of your establishment.",
"<strong>Establishment type:</strong>",
"To finish the installation click here",
"Send",
"Error creation %1 (%2)",
"<strong>Intranet customization</strong>",
"choose a configuration:",
"<strong>Theme:</strong>",
"Apply to the menus",
"<strong>graphic bullets:</strong>",
"<strong>graphic background:</strong>",
"apply to the page",
"<strong>Titles' bar:</strong>",
"<strong>Banner color:</strong>",
"<strong>Address:</strong>",
"<strong>Logos:</strong>",
"<a href=\"%1\">main logo</a>",
"Left",
"Center",
"Right",
"<strong>Window's title:</strong>",
"<strong>Welcome message:</strong>",
"Connection:",
"help",
"link modification",
"new link",
"insertion",
"modification",
"<strong>Menus manager</strong><br/><em>Please fill in the following form to customize the link</em>",
"<strong>Status:</strong>",
"<strong>author:</strong>",
"<strong>List:</strong>",
"<strong>Beware:</strong> the heading must be filled in.",
"<strong>Heading</strong>",
"<strong>Beware:</strong> the URL must be filled in.",
"<strong>URL</strong> (an Internet address must begin by http://)",
"<strong>Visible access</strong>",
"<strong>authorizations</strong>",
"Close link",
"Anonymous Access",
"Add link",
"Back to previous page.",
"- public:",
"- validity:",
"<a href=\"%1\" onclick=\"window.open(this.href, '_blank'); return false;\">region logo</a>",
"Authorized Languages:",
"<strong>Image</strong>",
"add a menu",
"modify a menu",
"new menu",
"<strong>Text</strong>",
"<strong>Alignment</strong>",
"<strong>Display</strong>",
"close menu",
"scrolling",
"Welcome on the %1 homepage",
"<strong>Pictogram</strong>",
"<strong>Content</strong>",
"<strong>. SMS</strong>",
"SMS service:",
"<strong>Webmaster:</strong>",
"install",
"uninstall",
"P2P",
"<strong>Key:</strong>",
"Connection",
"Get a key",
"<strong>Sharing:</strong>",
"<strong>Maintenance:</strong>",
"choose a center:",
"<strong>Screening:</strong>",
"<strong>Access screening</strong>",
"from",
"to",
"yyyy-mm-dd",
"Encoding:",
"== customize ==",
"Backoffice",
"sort items",
"Activated",
"Deactivated",
"<strong>Size</strong>",
"Kb",
"<strong>Server:</strong>",
"<strong>P2P configuration</strong>",
"<strong>Menus configuration</strong>",
"<strong>Keywords configuration</strong>",
"Keywords",
"<strong>Synchronization:</strong>",
"run synchronization",
"Documents",
"Directory",
"<strong>Web crawler:</strong>",
"<strong>Zip code + city:</strong>",
"Time Zone",
"Architecture",
"bits",
"[new]",
"[reply]",
"[validate]",
"[cancel]",
"<strong>Top color line :</strong>",
"Timetable",
"Holidays",
"Week configuration pair/odd",
"Holidays configuration",
"Color",
"Week",
"to"
);
//---------------------------------------------------------------------------
?>
