<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : resource.php
 *		projet   : messages definition
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 11/04/2007
 *		modif    : 
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"<strong>On line Resources</strong>",
"The resources are available under different <a href=\"#\" onclick=\"popWin('format.php', '350', '200'); return false;\">formats</a>.",
"choose a resources server:",
"root folder",
"Modify",
"Create",
"Add a folder",
"<strong>Size</strong>",
"Main folder",
"Add",
"Send",
"Rename",
"Add a document",
"<strong>Documents Management::%1</strong><br/><em>Please fill in the following form to customize a ressource</em>",
"<strong>Status:</strong>",
"<strong>Folder:</strong>",
"<strong>Resources:</strong>",
"<strong>Close ressource</strong>",
"<strong>Moderator</strong>",
"<strong>Writers</strong>",
"<strong>Readers</strong>",
"none",
"the user must be declared beforehand as a moderator.",
"Modify a resource.",
"Cancel and quit.",
"<strong>Online Resources::File</strong><br/><em>Please fill in the following form to post your resource</em>",
"Modification",
"new recording",
"<strong>Title:</strong>",
"<strong>URL:</strong>",
"<strong>language:</strong>",
"<strong>Description:</strong>",
"<strong>Keywords:</strong>",
"<strong>author:</strong>",
"<strong>License:</strong>",
"<strong>Content:</strong>",
"<strong>Level:</strong>",
"<strong>Subject:</strong>",
"to save your data entry.",
"<strong>Documents management::%1</strong><br/><em>To create a file please fill in the following form</em>",
"<strong>Close folder</strong>",
"to %1 a file.",
"Return to resources page.",
"<strong>Resources on line</strong>",
"Create a new file",
"Choose a resource:",
"All resources",
"Choose a level:",
"All levels",
"Add a resource.",
"Launch research",
"Any type of contents",
"<strong>hit</strong>",
"more",
"<strong>Created on:</strong>",
"<strong>Modified on:</strong>",
"Remove this resource?",
"previous",
"next",
"<strong>Resources</strong><br/><em>To add a notice, please fill in the following form</em>",
"Cancel the message",
"<strong>Text</strong>",
"help",
"Add a notice.",
"Return to resources pages.",
"<strong>Resources area %1</strong><br/><em>Please fill in the following form to post your resource</em>",
"Resource modification",
"New resource",
"transfer",
"insertion",
"Cannot find the file.",
"<strong>Category:</strong>",
"<strong>Beware:</strong> the heading must be filled in.",
"<strong>Heading</strong> (the name of the resource in the table)",
"<strong>Description</strong> (optional)",
"the file size is limited to %1 bytes. Please change file.",
"you must indicate a file to download.",
"this file type is not authorized.",
"the file to be downloaded already exists on the server. Please change its name or its version #.",
"<strong>Beware:</strong> %1",
"<strong>File</strong> (click on the button to indicate the file to transfer)",
"<strong>Version</strong> (optional: file version #)",
"easy,average,difficult",
"Exercices level",
"<strong>Resources sharing</strong> (optional)",
"Return to %1  page.",
"<strong>Online Ressources:: File</strong>",
"[next].[previous]",
"<a href=\"%1\">return</a>",
"<strong>Documents:: %1</strong>",
"choose a _CLASS:",
"choose a group:",
"all _CLASSes",
"all groups",
"new",
"<strong>Document</strong>",
"<strong>date</strong>",
"Format",
"Modify",
"Modify resource",
"Close",
"Open",
"<a href=\"%1\">search</a> a resource.",
"Remove %1?",
"<strong>Version:</strong>",
"<strong>Resource:</strong>",
"%1 comment%s",
"Cannot rename the directory: %1",
"Cannot erase the directory: %1",
"Cannot erase the file: %1",
"Cannot rename the file: %1",
"Delete file?",
"Key Word",
"<strong>Form:</strong>",
"You will find here a bank of online resources.",
"%1 folder%s",
"%1 document%s",
"copy file",
"Copy",
"move file",
"Move",
"<strong>Last download:</strong>",
"close window",
"validate the data entry.",
"<strong>Note</strong>",
"<strong>Date of validity</strong> (optional)",
"by date,by name,by size",
"Connection",
"<strong>Autorization</strong>",
"comments",
"<strong>Priority:</strong>",
"Significant,High,Very high",
"<strong>Inform</strong>",
"do not inform,administrator,post-it,email",
"[%1] file upload",
"A new file has been uploaded in: \"%1\" on %2.",
"collaborative document",
"Lock document",
"<strong>Locked by:</strong> %1<br/><strong>Limit:</strong> %2",
"<strong>Lock</strong>",
"hour(s)",
"RSS",
"<strong>Usability</strong>",
"Visual,Auditive,Kinesthesic",
"%1 in",
"or",
"<strong>Menu</strong>",
"Attachment",
"(part %1)",
"<strong>Center:</strong>",
"all centers",
"briefcase",
"add to briefcase",
"Currently, you have %1 document%s in your briefcase.",
"What do you want to do:",
"export in a zipped file,copy in my work space",
"A zip file is <a href=\"%1\">available</a> with gz format.",
"Importance level",
"<strong>Color code</strong>",
"delete",
"resources|folder",
"<strong>Preferences</strong>",
"Private Folder",
"reset",
"Multicenters sharing",
"[new]",
"[reply]",
"[validate]",
"[cancel]"

);
//---------------------------------------------------------------------------
?>
