<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : stage.php
 *		projet   : messages definition
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 09/04/2007
 *		modif    : 
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"Close this window",
"<strong>Results</strong>",
"<strong>found training courses:</strong>",
"[previous]<strong>.</strong>[next]",
"<strong>Company/Firm</strong>",
"<strong>City:</strong>",
"<strong>Main activity:</strong>",
"<strong>N/H</strong>",
"<strong>Management of training courses menu</strong><br/><em>Please, fill in the following form to customize the training courses menu</em>",
"<strong>Status:</strong>",
"<strong>Menu</strong>",
"<strong>Close menu</strong>",
"<strong>Moderator</strong>",
"<strong>Writer</strong>",
"<strong>Readers</strong>",
"none",
"the user must be declared beforehand as a moderator.",
"Modify a training courses.",
"Cancel and quit.",
"<strong>Descriptive file</strong><br/><em>Please, fill in the following form to create a new file</em>",
"<strong>Activity area:</strong>",
"<strong>Corporate name:</strong>",
"<strong>Law status </strong>",
"(LIMITED LIABILITY COMPANY, LTD, PLC,...)",
"<strong>Adress:</strong>",
"<strong>Beware:</strong> you must fill in correctly the postal code",
"<strong>Postal code:</strong>",
"<strong>Phone:</strong>",
"<strong>Fax:</strong>",
"<strong>Manager:</strong>",
"<strong>Trainee's supervisor:</strong>",
"<strong>Company size:</strong>",
"(nbr of employees)",
"<strong>Period of work or rush:</strong>",
"<strong>Underage trainee accepted:</strong>",
"yes",
"no",
"<strong>Strong work:</strong>",
"<strong>housed trainee:</strong>",
"<strong>nourished trainee:</strong>",
"<strong>Training course adapted to speciality:</strong>",
"<strong>Comment:</strong>",
"<strong>Labour force</strong>",
"<strong>Number of UTH:</strong>",
"<strong>Landed</strong>",
"<strong>Whole area:</strong>",
"<strong>Under cultivation usable area:</strong>",
"<strong>Main fodder area:</strong>",
"<strong>Arable land:</strong>",
"<strong>Extra-professional commitments:</strong>",
"<strong>Subject to VAT:</strong>",
"<strong>Accountancy over two years:</strong>",
"<strong>Soil job carried out on cultivation usable area:</strong>",
"<strong>. Animal production</strong>",
"Category",
"Race",
"Female",
"Products destination",
"UPRa",
"Perf. control",
"Quality logo",
"Leisure",
"Competition",
"Breeding",
"Add a production",
"<strong>. Vegetables productions </strong>",
"self consumption",
"Sold",
"<strong>. Complementary workshops </strong>",
"Size",
"Add a workshop",
"<strong>Trainee activities</strong>",
"<strong>Passage in several departments:</strong>",
"<strong>Reception activities:</strong>",
"<strong>Animation activities:</strong>",
"<strong>Catering ctivities:</strong>",
"<strong>Other departments:</strong>",
"<strong>Activities to be negotiated:</strong>",
"Validate your datas.",
"<strong>Link file</strong>",
"<strong>Name:</strong>",
"<strong>Company:</strong>",
"Work completed",
"Comment of the training course supervisor",
"<strong>searching of training course</strong>",
"<strong>County:</strong>",
"First two digits",
"<strong>from %1 to %2:</strong>",
"Cancellation of %1?",
">>> Training course place",
"Launch research.",
"<strong>Training courses visits</strong>",
"choose a center:",
"to subscribe, choose a _CLASS:",
"all _CLASSes",
"Respond to a new convention",
"Create a new training course <em>(period %1)</em>.",
"training course period: %1",
"next",
"previous",
"<strong>_STUDENT</strong>",
"<strong>Place</strong>",
"<strong>Beginning</strong>",
"<strong>End</strong>",
"<strong>visit</strong>",
"Cancel your subcription concerning %1?",
"Confirm the datas entered.",
"<strong>Descriptive file</strong>",
"Training courses periods",
"Modify",
"<strong>File #:</strong>",
"Return to list",
"Assign a training course.",
"Return to research",
"modification",
"Comment of %1",
"Phone",
"Appointment",
"visited on",
"created on",
"Assign %1 to black list?",
"Remove %1 from black list?",
"Cancel this file?",
"new area",
"Cancel",
"<strong>Beware:</strong> you must fill in the corporate name field",
"<strong>Beware:</strong> you must fill in the city field",
"<strong>Beware:</strong> you must fill in the manager field",
"Suppression of production %1?",
"Suppression of category %1?",
"Removal of workshop %1?",
"Add",
"insertion",
"<strong>Email:</strong>",
"<strong>Web site:</strong>",
"<strong>List of CV</strong>",
"If you have already an company account: you can contact this candidate through your company account.<br/>
If you do not have a Login yet, create an account. Belonging to professional workspace enables you to contact the candidates.",
"<strong>Date:</strong>",
"<strong>Job: </strong>",
"<strong>Region: </strong>",
"<strong>Contract: </strong>",
"<strong>Hit</strong>",
"to reach my CV. ",
"<strong>Datas of CV</strong>",
"<strong>. Get in touch</strong>",
"<strong>. Career</strong>",
"<strong>. Job description</strong>",
"<strong>Name, first name:</strong>",
"<strong>Date of birth:</strong>",
"<strong>Address:</strong>",
"<strong>Country: </strong>",
"Mr., Mrs.",
"<strong>Work experiences:</strong>",
"<strong>Diplomas: </strong>",
"<strong>Foreign languages: </strong>",
"<strong>Diverse:</strong>",
"<strong>Date of availability:</strong>",
"<strong>Exact location:</strong>",
"<strong>Salary:</strong>",
"Exact job: ",
"Describe in some lines the profile of the job you seek:",
"<strong>Status:</strong> %1",
"<strong>Years of experience:</strong>",
"modification",
"record your input.",
"cancel or leave.",
"-- indifferent --",
"mandatory",
"incorrect email",
"you must indicate your name",
"you must indicate your date of birth",
"<strong>Company (city):</strong>",
"<strong>Task realized:</strong>",
"<strong>Date of beginning:</strong>",
"<strong>Date of departure:</strong>",
"<strong>Year of obtaining:</strong>",
"<strong>Details:</strong>",
"<strong>Language:</strong>",
"<strong>Level:</strong>",
"(aaaa-mm)",
"delete",
"modify",
"publish the CV",
"since",
"help",
"by",
"<strong>CV # %1 from %2</strong>",
"(%1 years)",
"return to the list of CV",
"<strong>Exp. :</strong>",
"<strong>List of offers</strong>",
"create an offer.",
"<strong>Offer input</strong>",
"publish the offer",
"Describe the company in some lines:",
"you must indicate the company name",
"incorrect address",
"If you have already an account: you can publish your annonces directly.<br/>
Otherwise you will be able to activate it after validation of your account.",
"<strong>Offer # %1 from %2</strong>",
"return to the list of offers",
"new offer",
"<strong>Authorization</strong>",
"RSS",
"<strong>Firstname:</strong>",
"<strong>Picture:</strong>",
"<strong>_CLASS:</strong>",
"[new]",
"[reply]",
"[validate]",
"[cancel]"

);
//---------------------------------------------------------------------------
?>
