<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : user.php
 *		projet   : messages definition
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 21/03/2007
 *		modif    : 
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"<strong>ACL management::%1</strong>",
"choose a center:",
"choose a category:",
"<strong>Group</strong>",
"<strong>connected users</strong>",
"Disconnect everyone!",
"<strong>last connection:</strong>",
"close window",
"choose a _CLASS:",
"all _CLASSes",
"<strong>HSL</strong>",
"<strong>Mobile:</strong>",
"Persistent connection",
"Validate changes.",
"all categories",
"<strong>Access to Intranet portal</strong>",
"The site is temporarily inaccessible due to maintenance.<br/>Thank you for coming back later.",
"The installation was not performed yet.<br/>If you really are the webmaster of this site, <a href=\"%1\">click here</a> to customize the Intranet.",
"No account yet? You can create <a href=\"%1\">one</a>.",
"<strong>Connection not authorized:</strong> the site is currently in maintenance.",
"<strong>Error:</strong> account closed or on standby for validation.",
"<strong>Error:</strong> the user ID or the password is incorrect. Please try again.",
"<strong>Password:</strong>",
"<strong>User ID :</strong>",
"then click here",
"<strong>User account</strong>",
"<strong>Beware:</strong> you must fill in this field.",
"<strong>Beware:</strong> your email is not valid. It must be in the following format: name@organisation.domain.",
"<strong>Error:</strong> this ID is already in use.",
"Thank you for your participation, see you soon.",
"<strong>WARNING:</strong>",
"<strong>HSL members:</strong>",
"without time limit",
"<strong>Duration:</strong>",
"<strong>Picture:</strong>",
"Validate your changes",
"Return on the banner page",
"existing session: %1",
"<strong>You have been disconnected.</strong>",
"<strong>The delay of this page has expired:</strong>",
"Add a recording",
"choose a promotion:",
"External,Intern,1/2 boarder,Campus",
"Grant holder",
"",
"E-portfolio",
"B2i-C2i",
"training courses",
"missings",
"<strong>_CLASS:</strong>",
"<strong>Name, first name:</strong>",
"<strong>Date: </strong>",
"Send a post-it",
"representative",
"next",
"<strong>Status:</strong>",
"previous",
"<strong>Interface customization</strong>",
"You can customize the presentation of your Digital WorkSpace and your services.",
"<strong>Menus:</strong>",
"<strong>Graphic chips:</strong>",
"<strong>graphic background:</strong>",
"customization",
"workspaces",
"my blog",
"my mail",
"my directories",
"my address book",
"Validate configuration.",
"Return to banner page.",
"<strong>_STUDENT account</strong>",
"<strong>Beware:</strong> you must fill in this field.",
"<strong>First name:</strong>",
"<strong>Gender:</strong>",
"<strong>Center:</strong>",
"Validate",
"<strong>Born on:</strong>",
"(yyyy-mm-dd)",
"<strong>Address:</strong>",
"<strong>Postal Code - City:</strong>",
"<strong>Phone:</strong>",
"Impossible to send an email.<br/>This account does not have any email.",
"<strong>Email:</strong>",
"<strong>Regime:</strong>",
"<strong>Grant:</strong>",
"<strong>Representative:</strong>",
"Yes",
"No",
"Never connected",
"Back to _STUDENT list",
"Add a recording",
"<strong>Role of everybody::%1</strong>",
"all centers",
"opened account",
"closed account",
"<strong>last connection</strong>",
"<strong>Title:</strong>",
"<strong>Function:</strong>",
"<strong>Validity:</strong>",
"%1 user%s on standby for <a href=\"%2\">validation</a>",
"Modify",
"<strong>RIGHTS</strong>",
"<strong>Registered on:</strong>",
"<strong>Last cnx:</strong>",
"<strong>Connected at:</strong>",
"messages",
"resources",
"connections",
"your password must have at least %1 characters.",
"your password is not filled in. For obvious safety reasons we recommend to fill in the field below.",
"Display",
"Hide",
"<strong>Signature:</strong>",
"<strong>Avatar:</strong>",
"<strong>Activity:</strong>",
"<strong>Category:</strong>",
"Authorize access to resource",
"Switch to black list",
"Refresh",
"",
"",
"to cancel these accounts",
"<strong>Subject: %1</strong>",
"Digital TextBook",
"<strong>Last access:</strong>",
"Disconnect %1?",
"<strong>Last click:</strong>",
"%1 min and %2 s",
"%1 seconds",
"modification",
"new recording",
"mandatory",
"Man",
"Woman",
"Anonymous",
"more",
"<strong>Representatives::%1</strong>",
"%1 years and %2 months",
"%1 months and %2 days",
"%1 days and %2 hours",
"%1 h and %2 min",
"%1 min and %2 S",
"%1 seconds",
"<strong>Language:</strong>",
"<strong>%1</strong> you have just created an account<br/>with login: <strong>%2</strong><br/>and password: <strong>%3 &nbsp;</strong><br/>Do not forget them!",
"The administrator will open your account soon. If you indicated a valid email, you will then automatically be informed.",
"You will receive a confirmation email containing your password to connect to your account.",
"Your account will have to be visited in the next %1 hours or it will be automatically cancelled.",
"Confirmation of your subscription on %1",
"
You will find below the password which will give access to your account on %1.
You will be able to modify it by clicking on the link \"My account\".
Your password: %2
",
"<strong>Lost password?</strong>",
"No problem. Fill in below your user ID.<br/>You will be sent an automatic Email with your password.",
"Send an email",
"Blacklist %1?",
"Delete user %1?",
"change _CLASS",
"change center",
"<strong>Telephone:</strong>",
"<strong>CV # %1</strong>",
"<strong>Offer # %1</strong>",
"<strong>Name:</strong>",
"Grant",
"<strong>Connection not authorized:</strong> your access is temporarily suspended.",
"screening by:|registration +|registration -|connection +|connection -",
"<strong>Passwords management</strong>",
"<strong>Format:</strong>",
"<strong>Regenerate:</strong>",
"Groups",
"if empty passwd",
"%1 account%s updated",
"Generate",
"waiting validation",
"Dates",
"Rights",
"[%1] New user awaiting",
"%1 is waiting for validation of his account.",
"%1 connection%s",
"Subjects",
"Language",
"2 columns,left,right",
"<strong>Titles Bar:</strong>",
"<strong>Restore:</strong>",
"default values",
"I lose my <a href=\"%1\">password</a>.",
"The ID you gave does not exist!",
"Your password has been sent.<br/>Look after your mail.",
"Internal error. Impossible to send an email.",
"Hello,

your subscription had been confirm.
You can lon on %1.
See you soon.",
"CSV export",
"<strong>Establishment:</strong> ",
"Zip code",
"record his establishment",
"Error: you must enter an establishment. Please try again.",
"ID",
"[new]",
"[reply]",
"[validate]",
"[cancel]"

);
//---------------------------------------------------------------------------
?>
