<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module    : config.php
 *		projet    : définition des messages
 *
 *		version   : 1.0
 *		auteur    : laporte
 *		creation  : 05/04/2007
 *		modif     : Fernando Cormenzana 22/07/2007 05:25:19 p.m. 
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"<strong>Configuración de la intranet</strong>",
"personalización",
"Base de datos",
"menús",
"<strong>. Seguridad</strong>",
"Conexión persistente:",
"Creación de la cuenta:",
"por los usuarios",
"Período de la validez:",
"de las cuentas (aaaa-mm-dd)",
"Filtración IP:",
"Modo DEBUG:",
"Modo DEMOSTRACIÓN:",
"(conexiones múltiples con la misma identificación)",
"Contraseña:",
"caractere(s)",
"Retraso para las páginas:",
"minuta",
"Retraso para los acoplamientos:",
"días",
"<strong>. Datos</strong>",
"Tamaño de los archivos:",
"Contingentes del disco:",
"Duración de los registros:",
"Duración del Stats:",
"Poste-él duración:",
"semanas",
"<strong>. Exhibición</strong>",
"Menús:",
"2 columnas,ido,derechas",
"Espaciamiento:",
"pixele(s)",
"Página de bandera:",
"Flash de la información del defecto",
"Datos por la página:",
"Número de páginas:",
"Mensajes pasados:",
"foro del estilo del egroup",
"<strong>. Documentos autorizados</strong>",
"Modificarte",
"Crear",
"- extensión:",
"agregar un documento",
"validar la configuración. ",
"de nuevo a la página de bandera. ",
"<strong>Configuración de la base de datos</strong>",
"<strong>. Centros constitutivos</strong>",
"visible",
"invisible",
"quitar",
"agregar un expediente",
"<strong>. Usuarios Groups</strong>",
"derechas extensas",
"limitó las derechas",
"<strong>. Clases/Curso/Formación</strong>",
"<strong>. Temas/UC/Módulos</strong>",
"<em>el para modificar tu Intranet para requisitos particulares, completa por favor el siguiente forma</em>",
"Prométhée, el « alistar para utilizar » EDT open source 100% libremente",
"Recepción en el Intranet",
"Mecanografiar por favor tu usuario de la identificación y tu contraseña a la muestra pulg.",
"Error con de la creación de \"%1\": comprobar si tienes las derechas para la escritura.",
"Error con la creación de %1: comprobar si tienes las derechas para la escritura.",
"¡Bien hecho, tuviste éxito en modificar tu Intranet para requisitos particulares! <br/><br/>
la única acción restante a proceder es crear las cuentas :<br/>
%1 de los usuarios con el phpMyAdmin (base de datos %2, tabula user_id). <br/>
%3 de los %4 con phpMyAdmin (la base de datos %5, tabula user_student). <br/><br/>
Para probar el Intranet, utilizar la cuenta del administrador el \"<strong>%6</strong>\" (ninguna contraseña).<br/>
Para firmar en ahora chascar <a href=\"%7\">aquí</a>.",
"opciones",
"elegir un menú:",
"nuevo título:",
"<strong>menú secundario</strong>",
"acoplamiento de la piel",
"acoplamiento de la exhibición",
"Personalización de la Intranet: %1/2",
"<strong>Beware :</strong> llenan por favor en nombre de tu establecimiento.",
"El nombre de tu establecimiento se utiliza para crear una carpeta images/logos/\"nombre\" donde la insignia de tu establecimiento (logo01.jpg) y tu región una (logo02.jpg) será copiada.",
"<strong>Nombre del establecimiento:</strong>",
"obligatorio",
"Aconsejó el tamaño máximo para la insignia del establecimiento: 700 x 110.",
"<strong>Insignia del establecimiento:</strong>",
"Aconsejó el tamaño máximo para la insignia de la región: 100 x 50.",
"<strong>Insignia del región:</strong>",
"El color del tema es el que está usado para el Intranet. Debe corresponder a tu carta gráfica.",
"<strong>Guardarte:</strong> indican por favor la dirección de tu establecimiento.",
"<strong>Dirección:</strong>",
"<strong>Guardarte:</strong> indican por favor el número de teléfono de tu establecimiento.",
"<strong>Teléfono:</strong>",
"<strong>Fax:</strong>",
"<strong>Website:</strong>",
"<strong>Email:</strong>",
"Indicar aquí tu tipo del establecimiento",
"después >>",
"La base de datos será modificada para requisitos particulares según tu establecimiento que type.<br/>Please indican los centros constitutivos (IE :High School secundaria menor e High School secundaria) cuáles son parte de tu establecimiento. ",
"<strong>Tipo del establecimiento:</strong>",
"Para acabar la instalación chascar aquí",
"Enviar",
"Error des creación %1 (%2)",
"<strong>Personalización de la Intranet</strong>",
"elegir una configuración:",
"<strong>Tema:</strong>",
"Aplicarte a los menús",
"<strong>balas gráfico:</strong>",
"<strong>fondo gráfico:</strong>",
"aplicarte a la página",
"<strong>Barra de los títulos:</strong>",
"<strong>Color de la bandera:</strong>",
"<strong>Dirección:</strong>",
"<strong>Insignia:</strong>",
"<a href=\"%1\">insignia principal</a>",
"Ido",
"Centro",
"Derecho",
"<strong>Título de la ventana:</strong>",
"<strong>Mensaje del recepción:</strong>",
"Conexión:",
"ayuda",
"modificación del acoplamiento",
"nuevo acoplamiento",
"inserción",
"modificación",
"<strong>Encargado de los menús</strong><br/><em>Completar por favor la forma siguiente para modificar el acoplamiento para requisitos particulares</em>",
"<strong>Estado:</strong>",
"<strong>autor:</strong>",
"<strong>Lista:</strong>",
"<strong>Guardarte:</strong> el título se debe llenar pulg.",
"<strong>Título</strong>",
"<strong>Guardarte :</strong> el URL se debe llenar pulg.",
"<strong>URL</strong> (un dirección internet debe comenzar por http://)",
"<strong>Acceso visible</strong>",
"<strong>Autorizaciones</strong>",
"Acoplamiento cercano",
"Acceso anónimo",
"Agregar el acoplamiento",
"De nuevo a la página anterior. ",
"- público:",
"- validez:",
"<a href=\"%1\" onclick=\"window.open(this.href, '_blank'); return false;\">insignia de la región</a>",
"Autorizó idiomas:",
"<strong>Imagen</strong>",
"agregar un menú",
"modificar un menú",
"nuevo menú",
"<strong>Texto</strong>",
"<strong>Alineación</strong>",
"<strong>Exhibición</strong>",
"menú cercano",
"enrollando",
"Recepción en el homepage %1",
"<strong>Cuadro</strong>",
"<strong>Contenido</strong>",
"<strong>. SMS</strong>",
"Servicio SMS:",
"<strong>Administrator:</strong>",
"Instalar",
"Desinstalación",
"P2P",
"<strong>Clave :</strong>",
"Conexión",
"Obtener una clave",
"<strong>Compartir :</strong>",
"<strong>Mantenimiento :</strong>",
"elija un centro :",
"<strong>Cribado :</strong>",
"<strong>Acceso cribado</strong>",
"de",
"a",
"aaaa-mm-dd",
"Codificación:",
"== Personalizar ==",
"Backoffice",
"ordenar los artículos",
"Activado",
"Desactivado",
"<strong>Tamaño</strong>",
"Ko",
"<strong>Servidor :</strong>",
"<strong>Configuración P2P</strong>",
"<strong>Configuración de menús</strong>",
"<strong>Configuración de Palabras clave</strong>",
"Palabras clave",
"<strong>Sincronización :</strong>",
"ejecutar la sincronización",
"Documentos",
"Anuario",
"<strong>Rastreador web :</strong>",
"<strong>Código postal + ciudad :</strong>",
"Huso horario",
"Arquitectura",
"bits",
"[nuevo]",
"[respuesta]",
"[validación]",
"[cancelar]"

);
//---------------------------------------------------------------------------
?>