<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : resource.php
 *		projet   : définition des messages
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 11/04/2007
 *		modif    : 11/08/2007 10:36:42 p.m. Fernando Cormenzana
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"<strong>Recursos en línea</strong>",
"Los recursos están disponibles bajo dintintos <a href=\"#\" onclick=\"popWin('format.php', '350', '200'); return false;\">formatos</a>.",
"Elija un servidor de recursos :",
"directorio raíz",
"Modificar",
"Crear",
"agregar un directorio",
"<strong>Tamaño</strong>",
"directorio padre",
"agregar",
"Enviar",
"Renombrar",
"agregar un documento",
"<strong>Gestión de los Documentos::%1</strong><br/><em>Sírvase completar el siguiente formulario para parametrizar un recurso</em>",
"<strong>Estado :</strong>",
"<strong>directorio :</strong>",
"<strong>recursos :</strong>",
"<strong>Cerrar el recurso</strong>",
"<strong>Moderador</strong>",
"<strong>Redactor</strong>",
"<strong>Lector</strong>",
"ninguno",
"El usuario debe ser un moderador o redactor.",
"para modificar un recurso.",
"para anular y salir.",
"<strong>recursos en línea::Ficha</strong><br/><em>Sírvase completar el siguiente formulario para publicar su recurso</em>",
"modificación",
"nuevo registro",
"<strong>Título :</strong>",
"<strong>URL :</strong>",
"<strong>idioma :</strong>",
"<strong>Descripción :</strong>",
"<strong>Palabras clave :</strong>",
"<strong>Autor :</strong>",
"<strong>Licencia :</strong>",
"<strong>Contenido :</strong>",
"<strong>Nivel :</strong>",
"<strong>Materias :</strong>",
"para guardar sus datos.",
"<strong>Gestión de los Documentos::%1</strong><br/><em>Sírvase completar el siguiente formulario para crear un directorio</em>",
"<strong>Cerrar el directorio</strong>",
"para %1 un directorio.",
"Para volver a la página de recursos.",
"<strong>recursos en línea</strong>",
"crear un nuevo directorio",
"elegir un recurso :",
"todos los recursos",
"elegir un nivel :",
"todos los niveles",
"para agregar un recurso.",
"Comenzar la búsqueda",
"todo tipo de contenido",
"<strong>vistos</strong>",
"plus",
"<strong>Creado el:</strong>",
"<strong>Modificado el:</strong>",
"¿Eliminar este recurso?",
"anterior",
"siguiente",
"<strong>recursos</strong><br/><em>Para agregar un anuncio, sírvase completar el siguiente formulario</em>",
"borrar el anuncio",
"<strong>Texto</strong>",
"ayuda",
"para agregar un anuncio.",
"para volver a la página de recursos.",
"<strong>Espacio recursos %1</strong><br/><em>Sírvase completar el siguiente formulario para publicar su recurso</em>",
"modificación de recursos",
"nuevo recurso",
"transferencia",
"inserción",
"ne se puede encontrar el archivo.",
"<strong>Categoría :</strong>",
"<strong>Atención :</strong> debe ingresar el título.",
"<strong>Título</strong> (el nombre del recurso en el cuadro)",
"<strong>Descripción</strong> (opcional)",
"el tamaño del archivo está limitado a %1 bytes. Sírvase cambiar de archivo.",
"debe indicar un archivo a transferir.",
"este tipo de archivo no está autorizado.",
"el archivoa transferir ya exsite en el servidor. Sírvase cambiar su nombre o el número de versión.",
"<strong>Atención:</strong> %1",
"<strong>Archivo</strong> (haga clic sobre el botón para indicar el archivo a transferir)",
"<strong>Versión</strong> (opcional: n° de versión del archivo)",
"fácil,medio,difícil",
"Nivel de los ejercicios",
"<strong>Compartir recursos</strong> (opcional)",
"para volver a la página %1.",
"<strong>recursos en línea::Archivo</strong>",
"[siguiente].[anterior]",
"<a href=\"%1\">volver</a>",
"<strong>Documentos::%1</strong>",
"elegir una _CLASS :",
"elegir un grupo :",
"todas las _CLASSs",
"todos los grupos",
"nuevo",
"<strong>Documento</strong>",
"<strong>Fecha</strong>",
"Formato",
"modificar",
"modificar el recurso",
"cerrar",
"abrir",
"<a href=\"%1\">buscar</a> un recurso.",
"¿Eliminar %1?",
"<strong>Versión :</strong>",
"<strong>recurso :</strong>",
"%1 comentario%s",
"No se puede renombrar el directorio : %1",
"No se puede eliminar el directorio : %1",
"No se puede eliminar el archivo : %1",
"No se puede renombrar el archivo : %1",
"¿Eliminación del archivo?",
"Palabra clave",
"<strong>Ficha:</strong>",
"Encontrará aquí un banco de recursos en línea.",
"carpeta%s",
"documento%s",
"copiar el archivo",
"Copiar",
"Mover el archivo",
"Mover",
"<strong>Última transferencia:</strong>",
"ventana cercana",
"validar la entrada de datos.",
"<strong>Observar</strong>",
"<strong>Fecha de validez</strong> (opcional)",
"por fecha,por nombre,por tamaño",
"Conexión",
"<strong>Autorización</strong>",
"comentarios",
"<strong>Prioridad :</strong>",
"Significativos,Alto,Muy alto",
"<strong>Informar</strong>",
"no informar,administrador,post-it,e-mail",
"[%1] carga de archivos",
"Un nuevo archivo se ha cargado en : \"%1\" el %2.",
"Documento de colaboración",
"Bloquear documento",
"<strong>Bloqueado por :</strong> %1<br/><strong>Límite :</strong> %2",
"<strong>Bloqueo</strong>",
"hora(s)",
"RSS",
"<strong>Usabilidad</strong>",
"Visual,Auditive,Kinesthesic",
"%1 en",
"o",
"<strong>Menú</strong>",
"Archivo adjunto",
"(parte %1)",
"<strong>Centro:</strong>",
"todos los centros",
"portafolio",
"añadir a el portafolio",
"Actualmente, usted tiene el %1 documento%s en su portafolio.",
"¿Qué quiere hacer?",
"exportar en un archivo comprimido,copia en mi espacio de trabajo",
"Un archivo zip es <a href=\"%1\">disponible</a> con el formato gz.",
"Nivel de importancia",
"<strong>Código colores</strong>",
"borrar",
"recursos|carpeta",
"<strong>Preferencias</strong",
"Carpeta privada",
"restablecer",
"Multi centros compartir",
"[nuevo]",
"[respuesta]",
"[validación]",
"[cancelar]"

);
//---------------------------------------------------------------------------
?>