<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : formación.php
 *		projet   : définition des messages
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 09/04/2007
 *		modif    : 12/08/2007 10:43:29 a.m. Fernando Cormenzana
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"cerrar esta ventana",
"<strong>Resultados</strong>",
"<strong>Formaciones encontradas :</strong>",
"[anterior]<strong>.</strong>[siguiente]",
"<strong>Empresa/Uso</strong>",
"<strong>Ciudad :</strong>",
"<strong>Principal actividad :</strong>",
"<strong>N/L</strong>",
"<strong>Gestión del menú de formaciones</strong><br/><em>Sírvase completar el siguiente formulario para parametrizar el menú de formaciones</em>",
"<strong>Estado :</strong>",
"<strong>Mení</strong>",
"<strong>Cerrar el menú</strong>",
"<strong>Moderador</strong>",
"<strong>Redactor</strong>",
"<strong>Lectores</strong>",
"ninguno",
"El usuario debe ser un moderador.",
"para modificar un recurso.",
"para anular o salir.",
"<strong>Ficha Descriptiva</strong><br/><em>Sírvase completar el siguiente formulario para crear una nueva ficha</em>",
"<strong>Sector de actividad</strong>",
"<strong>Razón social :</strong>",
"<strong>Situación jurídica :</strong>",
"(SARL, GAEC, ...)",
"<strong>Dirección :</strong>",
"<strong>Atención :</strong> debe ingresar correctamente el códgo postal",
"<strong>Código postal :</strong>",
"<strong>Teléfono :</strong>",
"<strong>Fax :</strong>",
"<strong>Director :</strong>",
"<strong>Responsable del becario :</strong>",
"<strong>Tamaño del a empresa :</strong>",
"(cant. de empleados)",
"<strong>Horario de trabajo o de punta:</strong>",
"<strong>Becario menor aceptado :</strong>",
"si",
"no",
"<strong>Trabajos físicos :</strong>",
"<strong>Becario con alojamiento :</strong>",
"<strong>Becario con alimentación :</strong>",
"<strong>formación adaptada a la actividad :</strong>",
"<strong>Comentario :</strong>",
"<strong>Mano de obra</strong>",
"<strong>Cantidad de UTH :</strong>",
"<strong>Foncier</strong>",
"<strong>Superficie total :</strong>",
"<strong>Superficie agrícola utilisable :</strong>",
"<strong>Superficie forrajera principal :</strong>",
"<strong>Tierras laborables :</strong>",
"<strong>Responsabilidades extra-profesionales :</strong>",
"<strong>Sujeto al Impuesto al Valor Agregado:</strong>",
"<strong>contabilidad sobre dos años :</strong>",
"<strong>Trabajo de la tierra realizado como S.A. :</strong>",
"<strong>. Producciones animales</strong>",
"Categoría",
"Raza",
"Hembras",
"Destino de los productos",
"UPRa",
"Contrel perf.",
"Sigla de calidad",
"Pasatiempo",
"Competición",
"Ganadería",
"para agregar una producción",
"<strong>. Producciones vegetales</strong>",
"Autoconsumo",
"Vendido",
"<strong>. Tallereas complementarios</strong>",
"Tamaño",
"para agregar un taller",
"<strong>Actividades del Becario</strong>",
"<strong>Pasaje por varios servicios :</strong>",
"<strong>Actividades de recepción :</strong>",
"<strong>Actividades de animación :</strong>",
"<strong>Actividades de restauración :</strong>",
"<strong>Otros servicios :</strong>",
"<strong>Actividades a negociar :</strong>",
"para validar sus datos.",
"<strong>Ficha de relación</strong>",
"<strong>Nombre :</strong>",
"<strong>Empresa :</strong>",
"Trabajos realizados",
"Comentarios del responsable",
"<strong>Búsqueda de formaciones</strong>",
"<strong>Departemento :</strong>",
"dos primeras cifras",
"<strong>del %1 al %2 :</strong>",
"¿Eliminación de %1?",
">>> lugar de formación",
"para lanzar una búsqueda.",
"<strong>Visitas de formaciones</strong>",
"elija un centro :",
"para inscribirse, elija una _CLASS :",
"todas las _CLASSs",
"Corresponde a una nueva convención",
"para crear una nueva formación <em>(período %1)</em>.",
"formación período : %1",
"siguiente",
"anterior",
"<strong>_STUDENT</strong>",
"<strong>Lugar</strong>",
"<strong>principio</strong>",
"<strong>fin</strong>",
"<strong>visita</strong>",
"¿Anular su inscripción respecto a %1?",
"para confirmar sus datos.",
"<strong>Ficha Descriptiva</strong>",
"períodos de formación",
"modificar",
"<strong>Ficha n° :</strong>",
"volver a la lista",
"atribuir una formación.",
"volver a la búsqueda",
"modificación",
"Comentario de %1",
"Tel.",
"Cita",
"visitado por",
"creado el",
"¿Pasar %1 a lista negra?",
"¿Quitar a %1 de la lista negra?",
"¿Borrar esta ficha?",
"nuevo sector",
"borrar",
"<strong>Atención :</strong> debe ingresar la razón social",
"<strong>Atención :</strong> debe ingresar la ciudad",
"<strong>Atención :</strong> debe ingresar el director",
"¿Eliminación de la producción %1?",
"¿Eliminación de la categoría %1?",
"¿Eliminación del taller %1?",
"Agregar",
"inserción",
"<strong>Correo Electrónico :</strong>",
"<strong>Sitio web :</strong>",
"<strong>Listado de los CV</strong>",
"Si usted ya posee una cuenta empresarial: contacte al candidato a través de su cuenta en la empresa.<br />
Si aún no tiene nombre de usuario, idetifíquese creando ahora su cuenta. Formar parte del espacio empresarial le permitirá de entrar en contacto con los candidatos.",
"<strong>Fecha :</strong>",
"<strong>Cargo :</strong>",
"<strong>Region :</strong>",
"<strong>Contrato :</strong>",
"<strong>Vistos</strong>",
"acceder a mi CV.",
"<strong>Ingreso de CV</strong>",
"<strong>. Datos personales</strong>",
"<strong>. Trayectoria</strong>",
"<strong>. Cargo deseado</strong>",
"<strong>Apellido, nombre :</strong>",
"<strong>Fecha de nacimiento :</strong>",
"<strong>Domicilio :</strong>",
"<strong>País :</strong>",
"Sr.,Sra.",
"<strong>Experiencia profesional :</strong>",
"<strong>Diplomas :</strong>",
"<strong>Idiomas :</strong>",
"<strong>Varios :</strong>",
"<strong>Fecha de disponibilidad :</strong>",
"<strong>Lugar exacto :</strong>",
"<strong>Remuneración :</strong>",
"Cargo exacto :",
"Describa en algunas líneas el perfil del cargo deseado :",
"<strong>Situación :</strong> %1",
"<strong>Años de experiencia :</strong>",
"modificación",
"guardar sus datos.",
"anular o salir.",
"-- indistinto --",
"obligatorio",
"correo electrónico incorrecto",
"debe ingresar su apellido",
"debe ingresar su fecha de nacimiento",
"<strong>Empresa (ciudad) :</strong>",
"<strong>Trabajos realizados :</strong>",
"<strong>Fecha de inicio :</strong>",
"<strong>Fecha de finalización :</strong>",
"<strong>Año de obtención :</strong>",
"<strong>Detalles :</strong>",
"<strong>Idioma :</strong>",
"<strong>Nivel :</strong>",
"(aaaa-mm)",
"suprimir",
"modificar",
"publicar ele CV",
"desde",
"ayuda",
"por",
"<strong>CV n° %1 del %2</strong>",
"(%1 años)",
"volver a la lista de CV",
"<strong>Exp. :</strong>",
"<strong>Listado de ofrecimientos</strong>",
"crear un ofrecimento.",
"<strong>Ingreso de un ofrecimiento</strong>",
"publicar el ofrecimiento",
"Describa la empresa en algunas líneas :",
"Debe indicar la razón social",
"dirección incorrecta",
"Si ya posee una cuenta empresarial puede publicar directamente sus anuncios.<br />
En caso contrario la podrá activar luego de la validación de su cuenta.",
"<strong>Ofrecimiento n° %1 del %2</strong>",
"volver al listado de ofrecimientos",
"nuevo ofrecimiento",
"<strong>Autorizaciones</strong>",
"RSS",
"<strong>Nombre :</strong>",
"<strong>Foto :</strong>",
"<strong>_CLASS :</strong>",
"[nuevo]",
"[respuesta]",
"[validación]",
"[cancelar]"

);
//---------------------------------------------------------------------------
?>