<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : student.php
 *		projet   : définition des messages
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 21/03/2007
 *		modif    : 12/08/2007 11:15:13 p.m. Fernando Cormenzana
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"<strong>Gestión de las ACL::%1</strong>",
"elija un centro :",
"elija une categoría :",
"<strong>Grupo :</strong>",
"<strong>usuarios conectados</strong>",
"¡desconectar a todos los usuarios!",
"<strong>última conexión :</strong>",
"cerrar esta ventana",
"elija una _CLASS :",
"todas las _CLASSs",
"Pasar a las antiguas _STUDENT",
"Pasar a _STUDENT",
"Indicar un login de conexión",
"para validar las modificaciones.",
"todas las categorías",
"<strong>Acceder al portal intranet</strong>",
"El sitio está temporalmente fuera de servicio por tareas de mantenimiento.<br/>Gracias por su comprensión.",
"La instalación aún no se ha realizado.<br/>Si es el webmaster de este sitio, <a href=\"%1\">haga clic aquí</a> para parametrizar la intranet.",
"¿Aún no tiene una cuenta? Puede <a href=\"%1\">crear una</a>.",
"<strong>conexión no permitida :</strong> el sitio está en mantenimiento.",
"<strong>Error :</strong> cuenta cerrada o en espera de validación.",
"<strong>Error :</strong> la identificación del ususario o la contraseña es incorrecta. Vuelva a intentarlo.",
"<strong>Contraseña :</strong>",
"<strong>Identificación del usuario :</strong>",
"luego haga clic aquí",
"<strong>Cuenta del usuario</strong>",
"<strong>Atención :</strong> debe completar este campo.",
"<strong>Atención :</strong> su email no es válido. Debe ser del tipo: nombre@organismo.dominio",
"<strong>Error :</strong> esta identificación ya está en uso",
"Gracias por su participación y hasta pronto.",
"<strong>Atención</strong>",
"<strong>Miembro CHS :</strong>",
"sin límite de tiempo",
"<strong>Duración :</strong>",
"<strong>Foto :</strong>",
"Para validar sus modificaciones",
"para volver a la página de inicio.",
"sesión existente : %1",
"<strong>Fue desconectado.</strong>",
"<strong>El plazo de esta página expiró : </strong>",
"agregar un registro",
"promoción :",
"Externo,Interno,1/2 pensionario,Campus",
"Becaria",
"Login",
"e-portfolio",
"B2i-C2i",
"formaciones",
"ausencias",
"<strong>_CLASS :</strong>",
"<strong>Apellido, nombre :</strong>",
"<strong>Fecha :</strong>",
"Enviar un post-it",
"delegado",
"siguiente",
"<strong>Estado :</strong>",
"anterior",
"<strong>Personalización de la interfase</strong>",
"Puede personalizar la presentación de su Espacio Numérico de Trabajo así como sus servicios.",
"<strong>Menúes :</strong>",
"<strong>Viñetas gráficas :</strong>",
"<strong>Fondo gráfico :</strong>",
"personalización",
"espacios de trabajo",
"mi blog",
"mi mensajería",
"mis anuarios",
"mi carné de direcciones",
"para validar la configuración.",
"para volver a la página de inicio.",
"<strong>Cuenta de _STUDENT</strong>",
"<strong>Atención:</strong> debe completar este campo.",
"<strong>Nombre :</strong>",
"<strong>Sexo :</strong>",
"<strong>Centro :</strong>",
"Validar",
"<strong>Nacido(a) el :</strong>",
"(aaaa-mm-dd)",
"<strong>Dirección :</strong>",
"<strong>CP - Ciudad :</strong>",
"<strong>Tel. :</strong>",
"<strong>Atención:</strong> la información debe corresponder a la estructura nombre@organismo.dominio",
"<strong>Email :</strong>",
"<strong>Régimen :</strong>",
"<strong>Beca :</strong>",
"<strong>Delegado :</strong>",
"Si",
"No",
"nunca se conectó",
"Para volver a la lista de _STUDENT",
"agregar un registro",
"<strong>El rol de cada uno::%1</strong>",
"todos los centros",
"cuenta abierta",
"cuenta cerrada",
"<strong>última conexión</strong>",
"<strong>Título :</strong>",
"<strong>Función :</strong>",
"<strong>Validez :</strong>",
"%1 usuario%s en espera de <a href=\"%2\">validación</a>",
"modificar",
"DERECHOS",
"<strong>Inscripto el :</strong>",
"<strong>Última conexión:</strong>",
"<strong>Conectado a :</strong>",
"mensajes",
"recursos",
"conexiones",
"su contraseña debe tener al menos  %1 caracteres.",
"debe indicar una contraseña. Sírvase completar el siguiente campo.",
"desplegar",
"ocultar",
"<strong>Firma :</strong>",
"<strong>Avatar :</strong>",
"<strong>Actividad :</strong>",
"<strong>Categoría :</strong>",
"Autorizar el acceso al recurso",
"Bascular a lista negra",
"actualizar",
"<strong>Lista _STUDENT::%1</strong>",
"<strong>Antiguos _STUDENT::%1</strong>",
"para borrar estos %1",
"<strong>Tema : %1</strong>",
"Libreta Numérico del profesor",
"<strong>último acceso :</strong>",
"¿ Desconectar %1?",
"<strong>último click :</strong>",
"%1 min y %2 s",
"%1 segundos",
"modificación",
"nuevo registro",
"obligatorio",
"Hombre",
"Mujer",
"Anónimo",
"mas",
"<strong>Los delegados::%1</strong>",
"%1 años y %2 meses",
"%1 mes y %2 días",
"%1 días y %2 horas",
"%1 h y %2 min",
"%1 min y %2 s",
"%1 segundos",
"<strong>Idioma :</strong>",
"<strong>%1</strong> acaba de crear una cuenta <br/>con identificación : <strong>%2</strong><br/>y como contraseña : <strong>%3 &nbsp;</strong><br/>¡¡NO LOS OLVIDE!!",
"El administrador validará su cuenta en poco tiempo. Si indicó un email válido, será avisado automáticamente.",
"Recibirá un email de confirmación que contendrá su contraseña para acceder a la cuenta.",
"Su cuenta deberá ser visitada en las próximas %1 horas o será automáticamente destruída.",
"Confirmación de su registro en %1",
"
Encontrará a continuación la contraseña que le permitirá acceder a su cuenta en %1.
Podrá modificarla haciendo clic sobre el vínculo \"Mi cuenta\".
Su contraseña es: %2
",
"<strong>¿Olvidó su contraseña?</strong>",
"No se preocupe. Indique a continuación su identificación como usuario.<br/>Un Email con su contraseña le será automáticamente enviado.",
"Enviar un email",
"¿Pasar a %1 a la lista negra?",
"¿Cancelación usuario %1?",
"cambiar la _CLASS",
"cambiar el centro",
"Teléfono:",
"<strong>CV n. %1</strong>",
"<strong>Oferta n. %1</strong>",
"<strong>Apellido :</strong>",
"Beca",
"<strong>conexión no permitida :</strong> su acceso es suspendido temporalmente.",
"Cribado por:|registro +|registro -|conexión +|conexión -",
"<strong>Gestión de contraseñas</strong>",
"<strong>Formato:</ b>",
"<strong>Regenerar:</strong>",
"Grupos",
"si contraseña vacía",
"%1 cuenta%s actualizado",
"Generar",
"espera validación",
"Fechas",
"Derechos",
"[%1] Nuevo usuario en espera",
"%1 está a la espera de la validación de su cuenta.",
"%1 conexión%s",
"Materias",
"(%1 años)",
"Borrar",
"Opciones",
"Status",
"O:Válida,N:Ex alumno,A:A la espera,D:Renunciar,E: Excluidos",
"exportar a CSV",
"<strong>N° de identificación:</strong>",
"<strong>CP</strong>",
"<strong>Ciudad</strong>",
"<strong>Lista de padres</strong>",
"<strong>Móvil:</strong>",
"<strong>Trabajo:</strong>",
"tutores",
"[nuevo]",
"[respuesta]",
"[validación]",
"[cancelar]"

);
//---------------------------------------------------------------------------
?>