<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : config.php
 *		projet   : définition des messages
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 05/04/2007
 *		modif    : 
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"<strong> Konfiguration Intranet </strong>",
"Personalisierung",
"Datenbank",
"Menüs",
"<strong>. Sicherheit </strong>",
"Persistent Connection",
"Benutzerkonto erstellen",
"Durch Benutzer",
"Gültig",
"Accounts (yyyy-mm-dd)",
"IP-Filter",
"Debug-Modus",
"Demo-Modus",
"(Mehrfachverbindungen mit der gleichen ID)",
"Passwort:",
"Character (s)",
"Time Seiten:",
"Minutes",
"Delay Links gilt:",
"Tage",
"<strong>. Daten </strong>",
"Dateigröße",
"Datenträgerkontingente:",
"Länge der Holzscheite:",
"Time Statistik:",
"Dauer der Post-it:",
"Wochen",
"<strong>. Anzeige </strong>",
"Menüs",
"2 Spalten, links, rechts",
"Spacing",
"Pixel (s)",
"Home",
"Newsflash default",
"Data Pro Seite:",
"Anzahl der Seiten:",
"Last Post",
"forum Stil Egroup",
"<strong>. Autorisierte Dokumente </strong>",
"Change",
"Erstellen",
"- Erweiterung",
"Add a document",
"Um die Konfiguration zu bestätigen.",
"Um nach Hause zurückzukehren.",
"<strong> Konfigurieren der Datenbank </strong>",
"<strong>. Konstituierende Zentren </strong>",
"Sichtbar",
"Invisible",
"Löschen",
"Datensatz hinzufügen",
"<strong>. Gruppen </strong>",
"Broad Rechte",
"Eingeschränkte Rechte",
"<strong>. Klassen / Sektoren / Training </strong>",
"<strong> / UV. Materialien / modules </strong>",
"<em>, um Ihren Intranet gestalten, füllen Sie bitte das Formular unten </ em>",
"Prometheus, HNO \'schlüsselfertige\' Lizenzfreie",
"Willkommen in Ihrem Intranet",
"Bitte geben Sie Ihren Benutzernamen und Passwort ein, um zu verbinden.",
"Fehler beim Erstellen \'%1 \': stellen Sie sicher, Sie Schreibzugriff haben.",
"Fehler beim Erstellen%1: sicherzustellen, dass Sie Schreibrechte haben.",
"Herzlichen Glückwunsch, Sie haben erfolgreich Ihr Intranet eingestellt! <br/>
Sie haben noch um die Konten zu erstellen <br/>
%1 der Nutzer mit phpMyAdmin (Basis %2, user_id Tabelle). <br/>
%3%4 mit phpMyAdmin (5% Basistabelle user_student). <br/>
Um das Intranet zu testen, verwenden Sie das Administrator-Konto \'<strong> 6% </strong> \' (ohne Passwort). <br/>
Sich jetzt einloggen klicken Sie hier <a href=\'%7\'> </a>. ",
"Optionen",
"Wählen Sie ein Menü:",
"Neue Namen",
"<strong> Untermenü </strong>",
"Hat den Link nicht angezeigt",
"Zeigen Sie den Link",
"Anpassen des Intranet: 02.01%",
"<strong>. Warnung: </strong> geben Sie bitte den Namen Ihrer Institution",
"Die \' name \'Ihrer Eigenschaft wird verwendet, um ein Verzeichnis images / logos / \ erstellen\' name \', die das Logo Ihrer Institution (logo01.jpg) sowie Region (logo02.jpg) kopiert werden. ",
"<strong> Name-Eigenschaft: </strong>",
"Obligatorische",
"Empfohlene logo Gründung Maximale Größe: 700 x 110",
"<strong> Logo Einrichtung: </strong>",
"Empfohlene Logo Region Maximale Größe: 100 x 50",
"<strong> Logo Fläche: </strong>",
"Das Farbthema ist, dass für das Intranet verwendet. Es muss Ihre Corporate Identity anzupassen.",
"<strong>. Warnung: </strong> geben Sie bitte die Adresse Ihrer Institution",
"<strong> Adresse: </strong>",
"<strong> Achtung: </strong> Bitte geben Sie die Telefon Ihrer Institution.",
"<strong> Tel: </strong>",
"<strong> Fax: </strong>",
"<strong> Website: </strong>",
"<strong> E-Mail: </strong>",
"Geben Sie hier die Art Ihres Unternehmens",
"Weiter >>",
"Die Datenbank wird abhängig von der Art Ihres Unternehmens <br/> Bitte geben Sie die Bestandteil Zentren (dh College und High School) .. Komponieren Ihr Unternehmen festgelegt werden",
"<strong> Eigentümer: </strong>",
"Um die Installation abzuschließen, klicken Sie hier",
"Senden",
"Fehler beim Erstellen%1 (%2)",
"<strong> Anpassen der Intranet </strong>",
"Wählen Sie eine Konfiguration:",
"<strong> Thema: </strong>",
"Auf der Menüs",
"<strong> Grafikchips: </strong>",
"<strong> Grafik-Hintergrund: </strong>",
"Auf der Seite",
"<strong> Bar-Titel: </strong>",
"<strong> Farbbalken: </strong>",
"<strong> Adresse: </strong>",
"<strong> Logos: </strong>",
"<a Href=\'%1\'> Hauptlogo </a>",
"Links",
"Zentriert",
"Rechts",
"<strong> Window Title: </strong>",
"<strong> Gruß: </strong>",
"Connection",
"Hilfe",
"Geänderte Relation",
"Neuer Link",
"Insertion",
"Modifikation",
"<strong> Menü-Manager </strong> <br/> <em> Bitte füllen Sie das folgende Formular aus um das </ em>",
"<strong> Status: </strong>",
"<strong> Autor: </strong>",
"<strong> Liste: </strong>",
"<strong> Achtung: </strong> der Titel müssen ausgefüllt werden.",
"<strong> Titel </strong>",
"<strong> Achtung: </strong> URL muss angegeben werden.",
"<strong> URL </strong> (eine Web-Adresse sollte mit http: //)",
"<strong> Zugang sichtbar </strong>",
"<strong> Berechtigungen </strong>",
"Schließen Sie die Verbindung",
"Anonymous Access",
"Link hinzufügen",
"Um zur vorherigen Seite zurückzukehren.",
"- Public:",
"- Gültigkeit:",
"<a href = \'%1 \'onclick = \' window.open (this.href, '_blank'); return false; \'> logo </a> Region",
"Sprachen erlaubt:",
"<strong> Bild </strong>",
"Menü hinzufügen",
"Menü \'Bearbeiten\'",
"Neues Menü",
"<strong> Text </strong>",
"<strong> Ausrichtung </strong>",
"<strong> View </strong>",
"Aus dem Menü",
"Scrolling",
"Willkommen in der %1.",
"<strong> Piktogramm </strong>",
"<strong> Inhalt </strong>",
"<strong>. SMS </strong>",
"SMS-Service",
"<strong> Webmaster: </strong>",
"Einrichten",
"Deinstallieren",
"P2P",
"<strong> Key: </strong>",
"Anschluss",
"Wie Sie einen Schlüssel",
"<strong> Sharing: </strong>",
"<strong> Wartung: </strong>",
"Wählen Sie ein Zentrum",
"<strong> Filter: </strong>",
"<strong> Filterung Zugang </strong>",
"The",
"At",
"yyyy-mm-dd",
"Encoding",
"== Benutzerdefinierte ==",
"Back Office",
"Sortieren Punkte",
"Ein",
"Disabled",
"<strong> Größe </strong>",
"Ko",
"<strong> Server </strong>",
"<strong> Konfiguration P2P </strong>",
"<strong> Menü Konfiguration </strong>",
"<strong> Konfigurieren Schlüsselwort </strong>",
"Stichwort",
"<strong> Sync: </strong>",
"Synchronisierung starten",
"Dokumente",
"Jahrbuch",
"<strong> Raupen: </strong>",
"<strong> PLZ + Ort: </strong>",
"Zeitzone",
"Architektur",
"Bits",
"[Neu]",
"[Adresse]",
"[Validate]",
"[Cancel]",
"<strong> Farbe Bandeau-Top-Menü: </strong>",
"Stundenplan",
"Ferien",
"Konfiguration Woche gerade / ungerade",
"Konfigurieren Urlaub",
"Farbe",
"Woche",
"At",
"Material der Klasse",
"Klassenlehrer",
"<strong>. Grund für Abwesenheit</strong>",
"Um anzugeben, dass das Fehlen sollte nicht berücksichtigt hinzufügen [NC] im Titel des Musters werden"

);
//---------------------------------------------------------------------------
?>
