<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : stage.php
 *		projet   : définition des messages
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 09/04/2007
 *		modif    : 
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"fermer cette fenêtre",
"<strong>Résultats</strong>",
"<strong>Stages trouvés :</strong>",
"[précédent]<strong>.</strong>[suivant]",
"<strong>Entreprise/Exploitation :</strong>",
"<strong>Ville :</strong>",
"<strong>Activité principale :</strong>",
"<strong>N/L</strong>",
"<strong>Gestion du menu des Stages</strong><br/><em>Veuillez compléter le formulaire suivant pour paramétrer le menu des stages</em>",
"<strong>Statut :</strong>",
"<strong>Menu</strong>",
"<strong>Fermer le menu</strong>",
"<strong>Modérateur</strong>",
"<strong>Rédacteur</strong>",
"<strong>Lecteurs</strong>",
"aucun",
"l'utilisateur doit être préalablement déclaré comme modérateur ou rédacteur.",
"pour modifier une ressource.",
"pour annuler et quitter.",
"<strong>Fiche Descriptive</strong><br/><em>Veuillez compléter le formulaire suivant pour créer une nouvelle fiche</em>",
"<strong>Secteur d'activité :</strong>",
"<strong>Raison sociale :</strong>",
"<strong>Statut juridique :</strong>",
"(SARL, GAEC, ...)",
"<strong>Adresse :</strong>",
"<strong>Attention :</strong> vous devez renseigner correctement le code postal",
"<strong>Code postal :</strong>",
"<strong>Téléphone :</strong>",
"<strong>Fax :</strong>",
"<strong>Directeur/Exploitant :</strong>",
"<strong>Responsable du stagiaire :</strong>",
"<strong>Taille de l'entreprise :</strong>",
"(nbr de salariés)",
"<strong>Période de travail ou de pointe :</strong>",
"<strong>Stagiaire mineur accepté :</strong>",
"oui",
"non",
"<strong>Travaux de force :</strong>",
"<strong>Stagiaire logé :</strong>",
"<strong>Stagiaire nourri :</strong>",
"<strong>Stage adapté à la filière :</strong>",
"<strong>Commentaire :</strong>",
"<strong>La main d'oeuvre</strong>",
"<strong>Nombre d'UTH :</strong>",
"<strong>Le foncier</strong>",
"<strong>Surface totale :</strong>",
"<strong>Surface Agricole Utilisable :</strong>",
"<strong>Surface Fourragère Principale :</strong>",
"<strong>Terres labourables :</strong>",
"<strong>Responsabilités extra-professionelles :</strong>",
"<strong>Assujettie à la TVA :</strong>",
"<strong>comptabilité sur deux ans :</strong>",
"<strong>Travail du sol réalisé sur SA :</strong>",
"<strong>. Productions animales</strong>",
"Catégorie",
"Race",
"Femelles",
"Devenir des produits",
"UPRa",
"Contrôle perf.",
"Sigle qualité",
"Loisir",
"Compétition",
"Elevage",
"pour ajouter une production",
"<strong>. Productions végétales</strong>",
"Autoconsommé",
"Vendu",
"<strong>. Ateliers complémentaires</strong>",
"Taille",
"pour ajouter un atelier",
"<strong>Les activités du stagiaire</strong>",
"<strong>Passage dans plusieurs services :</strong>",
"<strong>Activités d'accueil :</strong>",
"<strong>Activités d'animation :</strong>",
"<strong>Activités de restauration :</strong>",
"<strong>Autres services :</strong>",
"<strong>Activités à négocier :</strong>",
"pour valider votre saisie.",
"<strong>Fiche de liaison</strong>",
"<strong>Nom :</strong>",
"<strong>Entreprise :</strong>",
"Travaux réalisés",
"Commentaire du maître de stage",
"<strong>Recherche de stages</strong>",
"<strong>Département :</strong>",
"deux premiers chiffres",
"<strong>du %1 au %2 :</strong>",
"Suppression de %1 ?",
">>> lieu de stage",
"pour lancer la recherche.",
"<strong>Visites de stages</strong>",
"choisissez un centre :",
"pour vous inscrire, choisissez une _CLASS :",
"toutes les _CLASSs",
"Correspond à une nouvelle convention",
"pour créer un nouveau stage <em>(période %1)</em>.",
"stage période : %1",
"suivant",
"précédent",
"<strong>_STUDENT</strong>",
"<strong>Lieu</strong>",
"<strong>début</strong>",
"<strong>fin</strong>",
"<strong>visite</strong>",
"Annuler votre inscription concernant %1 ?",
"pour confirmer la saisie.",
"<strong>Fiche Descriptive</strong>",
"périodes de stages",
"modifier",
"<strong>Fiche n° :</strong>",
"revenir à la liste",
"attribuer un stage.",
"revenir à la recherche",
"modification",
"Commentaire de %1",
"Tel",
"RdV",
"visite par",
"créé le",
"Faire passer %1 en liste brûlée ?",
"Enlever %1 de la liste brûlée ?",
"Effacer cette fiche ?",
"nouveau secteur",
"effacer",
"<strong>Attention :</strong> vous devez renseigner la raison sociale",
"<strong>Attention :</strong> vous devez renseigner la ville",
"<strong>Attention :</strong> vous devez renseigner le directeur",
"Suppression de la production %1 ?",
"Suppression de la catégorie %1 ?",
"Suppression de l'atelier %1 ?",
"Ajouter",
"insertion",
"<strong>Email :</strong>",
"<strong>Site web :</strong>",
"<strong>Liste des CV</strong>",
"Si vous possédez déjà un compte entreprise : vous pouvez contacter ce candidat via votre compte société.<br />
Si vous n'avez pas encore de Login, identifiez vous en créant un compte. Faire partie de l'espace entreprise vous permet de contacter les candidats.",
"<strong>Date :</strong>",
"<strong>Poste :</strong>",
"<strong>Région :</strong>",
"<strong>Contrat :</strong>",
"<strong>Vus</strong>",
"accéder à mon CV.",
"<strong>Saisie de CV</strong>",
"<strong>. Coordonnées</strong>",
"<strong>. Parcours</strong>",
"<strong>. Poste recherché</strong>",
"<strong>Nom, prénom :</strong>",
"<strong>Date de naissance :</strong>",
"<strong>Adresse :</strong>",
"<strong>Pays :</strong>",
"M.,Mme",
"<strong>Expériences professionnelles :</strong>",
"<strong>Diplômes :</strong>",
"<strong>Langues étrangères :</strong>",
"<strong>Divers :</strong>",
"<strong>Date de disponibilité :</strong>",
"<strong>Lieu exact :</strong>",
"<strong>Rémunération :</strong>",
"Poste exact :",
"Décrivez en quelques lignes le profil du poste que vous recherchez :",
"<strong>Statut :</strong> %1",
"<strong>Années d'expérience :</strong>",
"modification",
"enregistrer votre saisie.",
"annuler ou quitter.",
"-- indifférent --",
"obligatoire",
"email incorrect",
"vous devez indiquer votre nom",
"vous devez indiquer votre date de naissance",
"<strong>Société (ville) :</strong>",
"<strong>Tâches réalisées :</strong>",
"<strong>Date de début :</strong>",
"<strong>Date de fin :</strong>",
"<strong>Année d'obtention :</strong>",
"<strong>Détails :</strong>",
"<strong>Langue :</strong>",
"<strong>Niveau :</strong>",
"(aaaa-mm)",
"supprimer",
"modifier",
"publier le CV",
"depuis",
"aide",
"par",
"<strong>CV n° %1 du %2</strong>",
"(%1 ans)",
"retour à la liste des CV",
"<strong>Exp. :</strong>",
"<strong>Liste des offres</strong>",
"créer une offre.",
"<strong>Saisie de l'offre</strong>",
"publier l'offre",
"Décrivez l'entreprise en quelques lignes :",
"vous devez indiquer la raison sociale",
"adresse incorrecte",
"Si vous possédez déjà un compte entreprise : vous pouvez publier directement vos annonces.<br />
Sinon vous pourrez l'activer après validation de votre compte.",
"<strong>Offre n° %1 du %2</strong>",
"retour à la liste des offres",
"nouvelle offre",
"<strong>Autorisation</strong>",
"RSS",
"<strong>Prénom :</strong>",
"<strong>Photo :</strong>",
"<strong>_CLASS :</strong>",
"[nouveau]",
"[répondre]",
"[valider]",
"[annuler]"

);
//---------------------------------------------------------------------------
?>