<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : student.php
 *		projet   : définition des messages
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 21/03/2007
 *		modif    : 
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"<strong> Management-ACL : %1 </strong>",
"Wählen Sie ein Zentrum",
"Wählen Sie eine Kategorie",
"<strong> Gruppen: </strong>",
"<strong> Benutzer online </strong>",
"Trennen Sie alle!",
"<strong> Letzter Login: </strong>",
"Fenster schließen",
"Wählen Sie eine _CLASS:",
"All _CLASSs",
"Switch im alten _STUDENT",
"Wechseln Sie zurück zu _STUDENT",
"Giving ein Login-Verbindung",
"Um die Änderungen zu bestätigen.",
"Alle Kategorien",
"<strong> Zum Digital Workspace </strong>",
"Die Seite ist vorübergehend nicht erreichbar wegen Wartungsarbeiten. <br/> Bitte kommen Sie später wieder.",
"Die Installation wurde nicht abgeschlossen. <br/> Wenn Sie der Webmaster dieser Seite sind, klicken Sie hier <a href=\'%1\'> </a> das Intranet setzen." ,
"Noch kein Konto? <a Href=\'%1\'> Sie können eine </a> zu schaffen.",
"<strong> Anschluss unbefugte: </strong> die Seite ist derzeit im Wartungsmodus.",
"<strong> Fehler: </strong> Konto geschlossen oder Genehmigung aussteht.",
"<strong> Fehler: </strong> die Benutzer-ID oder Passwort ist nicht korrekt Bitte versuchen Sie es ..",
"<strong> Passwort: </strong>",
"<strong> Benutzer: </strong>",
"klicken Sie hier",
"<strong> Benutzerkonten </strong>",
"<strong> Achtung: </strong> Sie müssen dieses Feld ausfüllen.",
"<strong> Achtung: </strong> Ihre E-Mail ist nicht gültig es ist wie folgt zusammengesetzt sein: .. Nom@organisme.domaine",
"<strong> Fehler: </strong> diese ID wird bereits verwendet.",
"Vielen Dank für Ihre Teilnahme und bis bald.",
"<strong> ACHTUNG: </strong>",
"<strong> CHS Mitglied: </strong>",
"Kein Zeitlimit",
"<strong> Zeit: </strong>",
"<strong> Foto: </strong>",
"Um die Änderungen zu übernehmen",
"Um auf die Homepage zurückkehren",
"Bestehende Sitzung : %1",
"<strong> Sie haben getrennt wurde. </strong>",
"<strong> Die Zeit, die abgelaufen ist: </strong>",
"Datensatz hinzufügen",
"Promotion",
"Externe, interne Halb Grenze Campus",
"Fellow",
"Login",
"E-Portfolio",
"B2i-C2i",
"Stages",
"Abwesenheiten",
"<strong> _CLASS: </strong>",
"<strong> Vollständiger Name: </strong>",
"<strong> Datum: </strong>",
"Schicken Sie ein Post-it",
"Delegate",
"Weiter",
"<strong> Status: </strong>",
"Zurück",
"<strong> Customizing </strong> Schnittstelle",
"Sie können die Präsentation Ihrer digitalen Arbeitsbereich und Ihre Dienstleistungen anpassen.",
"<strong> Menüs: </strong>",
"<strong> Grafikchips: </strong>",
"<strong> Grafik-Hintergrund: </strong>",
"Personalisierung",
"Arbeitsbereiche",
"Mein Blog",
"Meine Mail",
"Meine Bücher",
"Meine Adresse",
"Um die Konfiguration zu bestätigen.",
"Um nach Hause zurückzukehren.",
"<strong> Konto _STUDENT </strong>",
"<strong> Achtung: </strong> Sie müssen dieses Feld ausfüllen.",
"<strong> Name: </strong>",
"<strong> Geschlecht: </strong>",
"<strong> Center </strong>",
"Bestätigen",
"<strong> Born (e): </strong>",
"(yyyy-mm-dd)",
"<strong> Adresse: </strong>",
"<strong> CP - Stadt: </strong>",
"<strong> Tel: </strong>",
"<strong> Achtung: </strong> Eintrag muss nom@organisme.domaine entsprechen.",
"<strong> E-Mail: </strong>",
"<strong> Plans: </strong>",
"<strong> Börse: </strong>",
"<strong> Delegierte: </strong>",
"Ja, ich will",
"Ich nicht",
"Never verbunden",
"Um in die Liste _STUDENT zurückkehren",
"Datensatz hinzufügen",
"<strong> Die Rollen : %1 </strong>",
"Alle Zentren",
"Konto eröffnen",
"Account geschlossen",
"<strong> Letzter Login </strong>",
"<strong> Titel: </strong>",
"<strong> Funktion: </strong>",
"<strong> Gültigkeit: </strong>",
"%1 User%s erwartet Validierung <a href=\'%2\'> </a>",
"Ändern",
"<strong> Rechte </strong>",
"<strong> Anmeldedatum: </strong>",
"<strong> Letzte CNX: </strong>",
"<strong> Verbunden mit: </strong>",
"Meldungen",
"Ressourcen",
"Verbindungen",
"Das Passwort muss mindestens %1 Zeichen.",
"Ihr Passwort ist leer. Aus offensichtlichen Gründen der Sicherheit empfehlen wir, dass Sie das Eingabefeld unten abzuschließen.",
"Aufstecken",
"Ausblenden",
"<strong> Signatur: </strong>",
"<strong> Avatar: </strong>",
"<strong>: </strong>",
"<strong>: </strong>",
"Zugriff auf die Ressource",
"Switch verbrannt Liste",
"Aktualisieren",
"<strong> :: Liste _STUDENT :: %1 </strong>",
"<strong> Ehemalige _STUDENT :: %1 </strong>",
"Um diese zu löschen _STUDENT",
"<strong> Subject: %1 </strong>",
"Digital Booklet Texe",
"<strong> Letzter Zugang: </strong>",
"%1 abmelden?",
"<strong> letzten Klick: </strong>",
"1% Min und %2 s",
"%1 seconds",
"Modifikation",
"New Record",
"Obligatorische",
"Man",
"Woman",
"Anonymous",
"Plus",
"<strong> Die Schülervertreter :: %1 </strong>",
"%1 Jahren und %2 Monaten",
"%1 Monat und %2 Tage",
"%1 Tage und %2 Stunden",
"%1 h und %2 min",
"%1 Min und %2 s",
"%1 seconds",
"<strong> Sprache: </strong>",
"<strong>%1 </strong> Sie gerade erstellt ein Konto bei <br/> als Kennung: <strong>%2 </ strong> <br/> und das Passwort: <strong>%3 & nbsp; </ strong> <br/> nicht vergessen! ",
"Der Administrator wird Ihr Konto in Kürze öffnen. Wenn Sie eine gültige E-Mail-Adresse eingegeben haben, werden Sie automatisch informiert werden.",
"Sie erhalten eine Bestätigung per E-Mail mit Ihrem Passwort Zugriff auf Ihr Konto zu erhalten.",
"Ihr Konto muss in den nächsten 1% Stunden besucht werden, oder es wird automatisch zerstört werden.",
"Bestätigung Ihrer Anmeldung auf %1",
",
Sie werden das Passwort, mit denen Sie Ihr Konto bei %1 Zugang zu finden.
Sie können es, indem Sie auf den Link \'Mein Konto \' ändern.
Passwort: %2
",
"<strong> Passwort vergessen? </strong>",
"Kein Problem. Geben Sie hier unten Ihre Benutzer-ID. <br/> Eine automatische E-Mail mit Ihrem Passwort.",
"E-Mail senden",
"Switch %1 verbrannt Liste?",
"Delete User %1?",
"Change _CLASS",
"Change Center",
"<strong> Telefon: </strong>",
"<strong> CV Nr %1 </strong>",
"<strong> Angebot Nr %1 </strong>",
"<strong> Name: </strong>",
"Börse",
"<strong> Anschluss unbefugte: </strong> Ihr Zugang vorübergehend ausgesetzt.",
"Filtern nach: | + Registrierung | Registrierung - | +-Anschluss | Anschluss -",
"<strong> Verwalten von Kennwörtern </strong>",
"<strong> Format: </strong>",
"<strong> Rebuild: </strong>",
"Gruppen",
"Pwd wenn leer",
"%1 Konto%s geändert",
"Generieren",
"Vorbehaltlich der Bestätigung",
"Termine",
"Rechte",
"[%1] Neuer Benutzer wartet",
"Benutzer %1 erwartet Validierung von seinem Konto.",
"%1 Verbindung(en)",
"Stoff",
"(%1 Jahr)",
"Löschen",
"Optionen",
"Status",
"O: Gültig, N: Alumnus, A: Schwebende, D: ist zurückgetreten, E: Ausgeschlossen",
"CSV-Export",
"<strong> ID-Nr. </strong>",
"<strong> CP </strong>",
"<strong> City </strong>",
"<strong> Liste Eltern </strong>",
"<strong> Mobil: </strong>",
"<strong> Arbeit: </strong>",
"<strong> Tutoren </strong>",
"[Neu]",
"[Adresse]",
"[Validate]",
"[Cancel]",
"Alle",
"Filter"

);
//---------------------------------------------------------------------------
?>
